// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIDelete(arg1:string,arg2:string):Promise<string>;

export function APIGet(arg1:string,arg2:string):Promise<string>;

export function APIPost(arg1:string,arg2:string,arg3:string):Promise<string>;

export function APIPut(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetPredictedPosition():Promise<Record<string, number>>;

export function GetServerURL():Promise<string>;

export function IsConnected():Promise<boolean>;

export function IsStandalone():Promise<boolean>;

export function SendEnvelope(arg1:string,arg2:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function StepMove(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Record<string, number>>;
