// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIDelete(arg1, arg2) {
  return window['go']['app']['App']['APIDelete'](arg1, arg2);
}

export function APIGet(arg1, arg2) {
  return window['go']['app']['App']['APIGet'](arg1, arg2);
}

export function APIPost(arg1, arg2, arg3) {
  return window['go']['app']['App']['APIPost'](arg1, arg2, arg3);
}

export function APIPut(arg1, arg2, arg3) {
  return window['go']['app']['App']['APIPut'](arg1, arg2, arg3);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function GetPredictedPosition() {
  return window['go']['app']['App']['GetPredictedPosition']();
}

export function GetServerURL() {
  return window['go']['app']['App']['GetServerURL']();
}

export function IsConnected() {
  return window['go']['app']['App']['IsConnected']();
}

export function IsStandalone() {
  return window['go']['app']['App']['IsStandalone']();
}

export function SendEnvelope(arg1, arg2) {
  return window['go']['app']['App']['SendEnvelope'](arg1, arg2);
}

export function SetServerURL(arg1) {
  return window['go']['app']['App']['SetServerURL'](arg1);
}

export function StepMove(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StepMove'](arg1, arg2, arg3, arg4);
}
