// Code generated by cmd/genwire (go run ./cmd/genwire). DO NOT EDIT.
// Source of truth: internal/protocol/messages.go (+ internal/game structs it references).

export type MessageType =
  "join_world" |
  "move" |
  "chat" |
  "equip" |
  "unequip" |
  "set_jobs" |
  "set_hotbar" |
  "set_keybinds" |
  "add_friend" |
  "accept_friend" |
  "decline_friend" |
  "remove_friend" |
  "party_invite" |
  "party_accept" |
  "party_decline" |
  "party_leave" |
  "party_kick" |
  "action" |
  "set_target" |
  "dodge" |
  "set_save_point" |
  "use_world_skill" |
  "enter_house" |
  "leave_house" |
  "house_interact" |
  "house_storage_deposit" |
  "house_storage_withdraw" |
  "house_place_furniture" |
  "house_pick_furniture" |
  "set_camp_skin" |
  "pet_set_battle" |
  "pet_set_mount" |
  "pet_release" |
  "pet_command" |
  "mount_toggle" |
  "welcome" |
  "world_state" |
  "player_joined" |
  "player_left" |
  "player_moved" |
  "player_sync" |
  "chat_message" |
  "entity_state" |
  "social_state" |
  "party_invite_received" |
  "friend_request_received" |
  "reward_notice" |
  "combat_tick" |
  "combat_event" |
  "camp_state" |
  "house_state" |
  "house_return" |
  "region_changed" |
  "error" |
  "map_config";

/** Entity classes carried in WorldEntity.kind. */
export type EntityKind = "player" | "npc" | "pet";

export type Rarity = "common" | "rare" | "epic" | "legendary";

export interface Envelope {
  type: MessageType;
  payload?: unknown;
}

export interface JoinWorldPayload {
  player_name: string;
  race?: string;
  main_job?: string;
  sub_job?: string;
  job?: string;
  weapon?: string;
  appearance?: CharacterAppearance;
}

export interface CharacterAppearance {
  skin: string;
  face: string;
  hair: string;
  hair_color: string;
  cloth: string;
  cloth_color: string;
  weapon: string;
  weapon_color: string;
}

export interface SetJobsPayload {
  main_job: string;
  sub_job: string;
  job_changer_id: string;
}

export interface MovePayload {
  z?: number;
  jump?: boolean;
  x: number;
  y: number;
  facing?: number;
}

export interface ChatPayload {
  message: string;
}

export interface EquipPayload {
  item_id: string;
  slot?: string;
}

export interface UnequipPayload {
  slot: string;
}

export interface SetHotbarPayload {
  slot: string;
  kind: string;
  id: string;
}

export interface SetKeybindsPayload {
  keybinds: Record<string, string>;
}

export interface PlayerNamePayload {
  player_name: string;
}

export interface PartyKickPayload {
  member_id: string;
}

export interface ActionPayload {
  action_id: string;
  target_id: string;
  item_id?: string;
  actor_id?: string;
}

export interface PetIDPayload {
  pet_id: string;
}

export interface PetCommandPayload {
  command: string;
}

export interface SetTargetPayload {
  target_id: string;
}

export interface SetSavePointPayload {
  save_point_id: string;
}

export interface UseWorldSkillPayload {
  skill_id: string;
  save_point_id?: string;
}

export interface SkillInfo {
  id: string;
  name: string;
  mp_cost: number;
  heals: boolean;
  buffs: boolean;
  description: string;
  job?: string;
  category?: string;
  prereq?: string;
  weapon_reqs?: string[];
  unlocked: boolean;
  proficiency?: string;
  level: number;
  max_level: number;
  unlock_level: number;
  prof_exp?: number;
  prof_exp_next?: number;
  cast_time_ms?: number;
  cooldown_ms?: number;
  world_only?: boolean;
  passive?: boolean;
  combo_length?: number;
  target?: string;
  effects?: SkillEffect[];
}

export interface SkillEffect {
  kind: string;
  power?: number;
  stat?: string;
  status?: StatusEffectDef;
  world?: string;
}

export interface StatusEffectDef {
  kind: string;
  duration: number;
  potency: number;
  on_caster?: boolean;
}

export interface JobProgressInfo {
  id: string;
  name: string;
  abbr: string;
  category: string;
  level: number;
  xp: number;
  max_xp: number;
}

export interface StatBlock {
  hp: number;
  mp: number;
  str: number;
  dex: number;
  vit: number;
  int: number;
  md: number;
  mag?: number;
  agi?: number;
}

export interface HotbarBinding {
  kind: string;
  id: string;
}

export interface ProfileInfo {
  name: string;
  level: number;
  xp: number;
  max_xp: number;
  race?: string;
  main_job: string;
  sub_job: string;
  subjob_unlock_level: number;
  unlocked_jobs: string[];
  appearance?: CharacterAppearance;
  jobs: JobProgressInfo[];
  stats: StatBlock;
  inventory: Item[];
  house_storage?: Item[];
  house_storage_capacity?: number;
  camp_skin?: string;
  equipped: Record<string, string>;
  hotbar: Record<string, HotbarBinding>;
  skills: SkillInfo[];
  prof_levels?: Record<string, number>;
  prof_exp?: Record<string, number>;
  friends: string[];
  save_point_id?: string;
  save_point_name?: string;
  visited_save_points?: VisitedSavePoint[];
  keybinds?: Record<string, string>;
  pets?: PetRecord[];
  battle_pet_id?: string;
  mount_pet_id?: string;
}

export interface Item {
  id: string;
  name: string;
  kind: string;
  slot?: string;
  type?: string;
  consumable?: string;
  rarity: Rarity;
  level: number;
  qty?: number;
  stats?: Record<string, number>;
}

export interface VisitedSavePoint {
  id: string;
  name: string;
  map_name?: string;
  home?: boolean;
}

export interface PetRecord {
  id: string;
  kind: string;
  name: string;
  level: number;
  xp: number;
  caught_at?: number;
}

export interface WelcomePayload {
  player_id: string;
  profile: ProfileInfo;
  map?: MapSnapshot;
}

export interface MapSnapshot {
  scene3d?: Scene3D;
  id: string;
  name: string;
  overworld: OverworldMap;
  tiled_map?: string;
  portals?: MapPortal[];
  tile_overrides?: MapTileOverrides;
  terrain_layers?: MapTerrainLayers;
  origin_x: number;
  origin_y: number;
  neighbors?: MapNeighbor[];
}

export interface Scene3D {
  version: number;
  map: string;
  environment: Record<string, any>;
  objects: SceneObject[];
  prefabs: ScenePrefabAsset[];
  terrain: SceneTerrain;
}

export interface SceneObject {
  id: string;
  name: string;
  parent?: string;
  prefab: string;
  transform: SceneTransform;
  visible: boolean;
  props: Record<string, any>;
  components?: SceneComponents;
  prefabInstance?: ScenePrefabInstance;
}

export interface SceneTransform {
  position: number[];
  rotation: number[];
  scale: number[];
}

export interface SceneComponents {
  collider?: SceneCollider;
  npc?: SceneNPC;
  poi?: ScenePOI;
  item?: SceneItem;
}

export interface SceneCollider {
  enabled: boolean;
  shape: string;
  size: number[];
  offset: number[];
  isTrigger: boolean;
}

export interface SceneNPC {
  enabled: boolean;
  archetype: string;
  level: number;
  hostile: boolean;
  respawnSeconds: number;
}

export interface ScenePOI {
  enabled: boolean;
  type: string;
  label: string;
  interactionRadius: number;
  destinationMap: string;
}

export interface SceneItem {
  enabled: boolean;
  itemId: string;
  quantity: number;
  respawnSeconds: number;
}

export interface ScenePrefabInstance {
  assetId: string;
  nodeId: string;
  rootId: string;
  overrides: string[];
}

export interface ScenePrefabAsset {
  id: string;
  name: string;
  kind: string;
  revision: number;
  objects: SceneObject[];
}

export interface SceneTerrain {
  version: number;
  heights: Record<string, number>;
  cells: Record<string, string>;
  paints?: Record<string, ScenePaint>;
}

export interface ScenePaint {
  color: string;
  noise: number;
  trees: number;
  rocks: number;
  grass: number;
}

export interface OverworldMap {
  tile: number;
  cols: number;
  rows: number;
  cells: string;
}

export interface MapPortal {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface MapTileOverrides {
  map_id: string;
  layers: Record<string, Record<string, number>>;
  updated_at?: string;
}

export interface MapTerrainLayers {
  ground: number[];
  collision: number[];
}

export interface MapNeighbor {
  id: string;
  x: number;
  y: number;
}

export interface MapConfigPayload {
  map: MapSnapshot | null;
}

export interface WorldEntity {
  z: number;
  grounded: boolean;
  id: string;
  name: string;
  kind: EntityKind;
  sprite?: string;
  owner_id?: string;
  level?: number;
  x: number;
  y: number;
  facing?: number | string;
  hp: number;
  max_hp: number;
  mp?: number;
  max_mp?: number;
  stamina?: number;
  alive: boolean;
  engaged?: boolean;
  is_ally?: boolean;
  target_id?: string;
  statuses?: StatusSnapshot[];
  capturable?: boolean;
  skill_atb?: number;
  has_queued_action?: boolean;
  casting_skill_id?: string;
  cast_target_id?: string;
  cast_progress?: number;
  cast_time_ms?: number;
  cast_ends_at?: number;
  weapon?: string;
  sub_weapon?: string;
  main_job?: string;
  sub_job?: string;
  appearance?: CharacterAppearance;
  immune_until?: number;
  in_house?: boolean;
  house_owner?: string;
  mounted?: boolean;
  mount_sprite?: string;
}

export interface StatusSnapshot {
  kind: string;
  potency: number;
  remaining: number;
  shield_hp?: number;
}

export interface AtlasPayload {
  maps: AtlasMap[];
}

export interface AtlasMap {
  id: string;
  name: string;
  overworld: OverworldMap;
  pois: AtlasPOI[];
  origin_x?: number;
  origin_y?: number;
}

export interface AtlasPOI {
  id: string;
  kind: string;
  name: string;
  x: number;
  y: number;
}

export interface SavePoint {
  id: string;
  name: string;
  x: number;
  y: number;
}

export interface JobChanger {
  id: string;
  name: string;
  x: number;
  y: number;
}

export interface WorldStatePayload {
  entities: WorldEntity[];
  camps?: WorldCamp[];
  save_points: SavePoint[];
  job_changers: JobChanger[];
  map: OverworldMap;
}

export interface WorldCamp {
  owner_name: string;
  owner_id: string;
  x: number;
  y: number;
  skin: string;
}

export interface CampStatePayload {
  camps: WorldCamp[];
}

export interface EnterHousePayload {
  owner_name: string;
}

export interface HouseInteractPayload {
  target: string;
}

export interface HouseStorageMovePayload {
  item_id: string;
  qty?: number;
}

export interface HousePlaceFurniturePayload {
  item_id: string;
  col: number;
  row: number;
}

export interface HousePickFurniturePayload {
  furniture_id: string;
}

export interface SetCampSkinPayload {
  skin: string;
}

export interface HousePlayer {
  z: number;
  grounded: boolean;
  id: string;
  name: string;
  x: number;
  y: number;
  facing: number | string;
  owner?: boolean;
  pets?: HousePet[];
}

export interface HousePet {
  z: number;
  grounded: boolean;
  id: string;
  name: string;
  sprite?: string;
  x: number;
  y: number;
  facing: number;
}

export interface HousePOI {
  id: string;
  kind: string;
  name: string;
  x: number;
  y: number;
}

export interface HouseStatePayload {
  map?: MapSnapshot;
  owner_name: string;
  skin: string;
  map_cols: number;
  map_rows: number;
  walk_cols: number;
  walk_rows: number;
  walk_origin_col: number;
  walk_origin_row: number;
  tile_size: number;
  players: HousePlayer[];
  furniture: HouseFurniture[];
  pois: HousePOI[];
  storage?: Item[];
  storage_capacity?: number;
  is_owner: boolean;
}

export interface HouseFurniture {
  id: string;
  col: number;
  row: number;
  owner?: string;
  item: Item;
}

export interface HouseReturnPayload {
  reason?: string;
}

export interface RegionChangedPayload {
  region_id: string;
  name?: string;
}

export interface EntityStatePayload {
  entities: WorldEntity[];
}

export interface PlayerLeftPayload {
  id: string;
}

export interface PlayerMovedPayload {
  z: number;
  grounded: boolean;
  id: string;
  x: number;
  y: number;
  facing: number;
}

export interface ChatMessagePayload {
  from_id: string;
  from_name: string;
  message: string;
}

export interface ActionResult {
  actor_id: string;
  action_id: string;
  action_name: string;
  target_id: string;
  item_id?: string;
  success: boolean;
  damage?: number;
  heal?: number;
  mp_restored?: number;
  message?: string;
  status_applied?: StatusSnapshot[];
  cast_started?: boolean;
}

export interface PlayerReward {
  player_id: string;
  xp: number;
  sub_xp?: number;
  levels_gained: number;
  sub_levels_gained?: number;
  new_level: number;
  new_xp: number;
  max_xp: number;
  sub_new_level?: number;
  sub_new_xp?: number;
  sub_max_xp?: number;
  loot: Item[];
  passive?: boolean;
  party_bonus?: boolean;
}

export interface FriendInfo {
  name: string;
  online: boolean;
  level?: number;
  weapon?: string;
  in_combat?: boolean;
}

export interface PartyMember {
  id: string;
  name: string;
  level: number;
  weapon: string;
  leader: boolean;
  in_combat?: boolean;
}

export interface PartyInfo {
  id: string;
  leader_id: string;
  members: PartyMember[];
}

export interface PartyInvitePayload {
  from_id: string;
  from_name: string;
  party_id: string;
}

export interface FriendRequestPayload {
  from_id?: string;
  from_name: string;
}

export interface RewardNoticePayload {
  xp: number;
  passive?: boolean;
  victory: boolean;
  message: string;
}

export interface SocialStatePayload {
  friends: FriendInfo[];
  party?: PartyInfo;
  pending_invite?: PartyInvitePayload;
  pending_friend_requests?: FriendRequestPayload[];
  outgoing_friend_requests?: string[];
}

export interface ErrorPayload {
  message: string;
}

export interface CombatTickPayload {
  entities: WorldEntity[];
}

export interface CombatEventPayload {
  attacker_id: string;
  target_id: string;
  damage: number;
  heal?: number;
  mp_restored?: number;
  hit: boolean;
  message?: string;
  action_id?: string;
  action_name?: string;
  success?: boolean;
  cast_started?: boolean;
  cast_cancelled?: boolean;
  entities: WorldEntity[];
}

