/** Re-exports Heroes 99 character types used across the game. */
export type {
  CharacterAppearance,
  CharacterAnim,
  CharacterFacing,
  H99LayerId,
} from "./heroes99";

export {
  APPEARANCE_OPTIONS,
  DEFAULT_APPEARANCE,
  GAME_WEAPON_TO_H99,
  H99_ANIMS,
  H99_BATTLE_RING_RADIUS,
  H99_COLLISION_HALF_H,
  H99_COLLISION_HALF_W,
  H99_DISPLAY_HEIGHT,
  H99_DISPLAY_SCALE,
  H99_DISPLAY_WIDTH,
  H99_WORLD_RING_RADIUS,
  H99_FACING_DEFAULT,
  H99_LAYER_ORDER,
  H99_NAME_LABEL_Y,
  H99_SHEET,
  RACE_APPEARANCE_PRESETS,
  WIZARD_CLOTH,
  WIZARD_HAIR,
  appearanceFromRace,
  appearanceFromWire,
  appearanceOptionAt,
  appearanceOptionIndex,
  appearanceToWire,
  applyGameWeapon,
  H99_ORIGIN,
  appearanceKey,
  facingFromDelta,
  facingToFlipX,
  frameForAnim,
  layerOffsetX,
  layerOriginX,
  layerAssetPath,
  layerTextureKey,
  mergeAppearance,
} from "./heroes99";
