package game

// MundiTerrain — Clara Mundi's custom supplemental tileset
// (assets/tilesets/mundi/MundiTerrain.png, generated by
// tools/gen_mundi_terrain.py). It covers the biome gaps in the Pipoya set:
// snow/ice/sand/scree fills, pines + palms + a dead grey tree, and
// per-biome props. 32px tiles, 8 columns, 2x2 trees on rows 1-2 using the
// same TL,TR / BL,BR stamp layout as BaseChip.
const (
	MundiFirstTerrain = 6000 // firstgid — after LightShadow (5700)
	MundiTerrainTiles = 64
	MundiTerrainCols  = 8
)

// MundiTerrain local tile ids.
const (
	MundiLocalSnowFill   = 0
	MundiLocalPackedSnow = 1
	MundiLocalIce        = 2
	MundiLocalDuneSand   = 3
	MundiLocalBeachSand  = 4
	MundiLocalScree      = 5
	MundiLocalAsh        = 6
	MundiLocalPeat       = 7

	// 2x2 trees — top-left locals; bottoms are +8.
	MundiLocalPineTL     = 8
	MundiLocalPineSnowTL = 10
	MundiLocalPalmTL     = 12
	MundiLocalDeadGreyTL = 14

	// Props A.
	MundiLocalCactusTall  = 24
	MundiLocalCactusRound = 25
	MundiLocalSage        = 26
	MundiLocalSnowShrub   = 27
	MundiLocalReedsTall   = 28
	MundiLocalReedsShort  = 29
	MundiLocalIceCrystal  = 30
	MundiLocalBoulder     = 31

	// Props B.
	MundiLocalRockSpire    = 32
	MundiLocalSnowDrift    = 33
	MundiLocalFern         = 34
	MundiLocalVineBush     = 35
	MundiLocalSnowyRock    = 36
	MundiLocalCharredStump = 37
	MundiLocalMudMound     = 38
	MundiLocalDriftwood    = 39

	// Props C.
	MundiLocalWetRock     = 40
	MundiLocalShells      = 41
	MundiLocalObsidian    = 42
	MundiLocalLavaRock    = 43
	MundiLocalFrostFern   = 44
	MundiLocalMossyRock   = 45
	MundiLocalSkull       = 46
	MundiLocalStoneMarker = 47

	// Props D.
	MundiLocalGiantMushroom = 48
)

// MundiGID converts a MundiTerrain local tile id to a map GID.
func MundiGID(local int) int { return MundiFirstTerrain + local }

// Frequently used MundiTerrain GIDs.
var (
	MundiGIDSnow      = MundiGID(MundiLocalSnowFill)
	MundiGIDPackedSnow = MundiGID(MundiLocalPackedSnow)
	MundiGIDIce       = MundiGID(MundiLocalIce)
	MundiGIDDune      = MundiGID(MundiLocalDuneSand)
	MundiGIDBeach     = MundiGID(MundiLocalBeachSand)
	MundiGIDScree     = MundiGID(MundiLocalScree)
	MundiGIDAsh       = MundiGID(MundiLocalAsh)
	MundiGIDPeat      = MundiGID(MundiLocalPeat)
)

// MundiTreeStamps mirrors PipoyaTreeStamps ({TL,TR,BL,BR} locals):
// pine, snowy pine, palm, dead grey.
var MundiTreeStamps = []PipoyaTreeStamp{
	{8, 9, 16, 17},   // pine
	{10, 11, 18, 19}, // snowy pine
	{12, 13, 20, 21}, // palm
	{14, 15, 22, 23}, // dead grey
}

// IsMundiTreeTopLocal reports whether a local id is a 2x2 tree canopy
// (walk-under, drawn on the overhead layer).
func IsMundiTreeTopLocal(local int) bool { return local >= 8 && local <= 15 }

// IsMundiTreeLocal reports whether a local id is any part of a 2x2 tree.
func IsMundiTreeLocal(local int) bool { return local >= 8 && local <= 23 }

// MundiBlockingLocals are props stamped with collision (boulders, spires,
// stumps) — cells resolve to '#' like Pipoya rock clusters.
var MundiBlockingLocals = map[int]bool{
	MundiLocalBoulder:      true,
	MundiLocalRockSpire:    true,
	MundiLocalIceCrystal:   true,
	MundiLocalObsidian:     true,
	MundiLocalSnowyRock:    true,
	MundiLocalWetRock:      true,
	MundiLocalMossyRock:    true,
	MundiLocalStoneMarker:  true,
	MundiLocalCharredStump: true,
	MundiLocalCactusTall:   true,
	MundiLocalCactusRound:  true,
	MundiLocalGiantMushroom: true,
}

// mundiLocalChar resolves a MundiTerrain local tile id to a terrain char.
// Blocking props map to grass — the collision layer turns the cell to '#',
// matching how Pipoya props resolve.
func mundiLocalChar(local int) (byte, bool) {
	switch {
	case local < 0 || local >= MundiTerrainTiles:
		return 0, false
	case local == MundiLocalSnowFill || local == MundiLocalPackedSnow:
		return TileSnow, true
	case local == MundiLocalIce:
		return TileIce, true
	case local == MundiLocalDuneSand || local == MundiLocalBeachSand:
		return TileSand, true
	case IsMundiTreeLocal(local):
		return TileTree, true
	default:
		return TileGrass, true
	}
}
