// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: fantasy/v1/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterAppearance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skin          string                 `protobuf:"bytes,1,opt,name=skin,proto3" json:"skin,omitempty"`
	Face          string                 `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	Hair          string                 `protobuf:"bytes,3,opt,name=hair,proto3" json:"hair,omitempty"`
	HairColor     string                 `protobuf:"bytes,4,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`
	Cloth         string                 `protobuf:"bytes,5,opt,name=cloth,proto3" json:"cloth,omitempty"`
	ClothColor    string                 `protobuf:"bytes,6,opt,name=cloth_color,json=clothColor,proto3" json:"cloth_color,omitempty"`
	Weapon        string                 `protobuf:"bytes,7,opt,name=weapon,proto3" json:"weapon,omitempty"`
	WeaponColor   string                 `protobuf:"bytes,8,opt,name=weapon_color,json=weaponColor,proto3" json:"weapon_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterAppearance) Reset() {
	*x = CharacterAppearance{}
	mi := &file_fantasy_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterAppearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterAppearance) ProtoMessage() {}

func (x *CharacterAppearance) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterAppearance.ProtoReflect.Descriptor instead.
func (*CharacterAppearance) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterAppearance) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

func (x *CharacterAppearance) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *CharacterAppearance) GetHair() string {
	if x != nil {
		return x.Hair
	}
	return ""
}

func (x *CharacterAppearance) GetHairColor() string {
	if x != nil {
		return x.HairColor
	}
	return ""
}

func (x *CharacterAppearance) GetCloth() string {
	if x != nil {
		return x.Cloth
	}
	return ""
}

func (x *CharacterAppearance) GetClothColor() string {
	if x != nil {
		return x.ClothColor
	}
	return ""
}

func (x *CharacterAppearance) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *CharacterAppearance) GetWeaponColor() string {
	if x != nil {
		return x.WeaponColor
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Slot          string                 `protobuf:"bytes,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Consumable    string                 `protobuf:"bytes,6,opt,name=consumable,proto3" json:"consumable,omitempty"`
	Rarity        string                 `protobuf:"bytes,7,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Level         int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	Qty           int32                  `protobuf:"varint,9,opt,name=qty,proto3" json:"qty,omitempty"`
	Stats         map[string]int32       `protobuf:"bytes,10,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_fantasy_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Item) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetConsumable() string {
	if x != nil {
		return x.Consumable
	}
	return ""
}

func (x *Item) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Item) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Item) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Item) GetStats() map[string]int32 {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StatusSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Potency       float64                `protobuf:"fixed64,2,opt,name=potency,proto3" json:"potency,omitempty"`
	Remaining     int32                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	ShieldHp      int32                  `protobuf:"varint,4,opt,name=shield_hp,json=shieldHp,proto3" json:"shield_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusSnapshot) Reset() {
	*x = StatusSnapshot{}
	mi := &file_fantasy_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSnapshot) ProtoMessage() {}

func (x *StatusSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSnapshot.ProtoReflect.Descriptor instead.
func (*StatusSnapshot) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *StatusSnapshot) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StatusSnapshot) GetPotency() float64 {
	if x != nil {
		return x.Potency
	}
	return 0
}

func (x *StatusSnapshot) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *StatusSnapshot) GetShieldHp() int32 {
	if x != nil {
		return x.ShieldHp
	}
	return 0
}

type SkillInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MpCost        int32                  `protobuf:"varint,3,opt,name=mp_cost,json=mpCost,proto3" json:"mp_cost,omitempty"`
	Heals         bool                   `protobuf:"varint,4,opt,name=heals,proto3" json:"heals,omitempty"`
	Buffs         bool                   `protobuf:"varint,5,opt,name=buffs,proto3" json:"buffs,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Job           string                 `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Prereq        string                 `protobuf:"bytes,9,opt,name=prereq,proto3" json:"prereq,omitempty"`
	WeaponReq     string                 `protobuf:"bytes,10,opt,name=weapon_req,json=weaponReq,proto3" json:"weapon_req,omitempty"`
	Unlocked      bool                   `protobuf:"varint,11,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	Level         int32                  `protobuf:"varint,12,opt,name=level,proto3" json:"level,omitempty"`
	MaxLevel      int32                  `protobuf:"varint,13,opt,name=max_level,json=maxLevel,proto3" json:"max_level,omitempty"`
	UnlockLevel   int32                  `protobuf:"varint,14,opt,name=unlock_level,json=unlockLevel,proto3" json:"unlock_level,omitempty"`
	Usage         int32                  `protobuf:"varint,15,opt,name=usage,proto3" json:"usage,omitempty"`
	UsageToNext   int32                  `protobuf:"varint,16,opt,name=usage_to_next,json=usageToNext,proto3" json:"usage_to_next,omitempty"`
	CastTimeMs    int32                  `protobuf:"varint,17,opt,name=cast_time_ms,json=castTimeMs,proto3" json:"cast_time_ms,omitempty"`
	WorldOnly     bool                   `protobuf:"varint,18,opt,name=world_only,json=worldOnly,proto3" json:"world_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillInfo) Reset() {
	*x = SkillInfo{}
	mi := &file_fantasy_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInfo) ProtoMessage() {}

func (x *SkillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInfo.ProtoReflect.Descriptor instead.
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *SkillInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkillInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillInfo) GetMpCost() int32 {
	if x != nil {
		return x.MpCost
	}
	return 0
}

func (x *SkillInfo) GetHeals() bool {
	if x != nil {
		return x.Heals
	}
	return false
}

func (x *SkillInfo) GetBuffs() bool {
	if x != nil {
		return x.Buffs
	}
	return false
}

func (x *SkillInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillInfo) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *SkillInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SkillInfo) GetPrereq() string {
	if x != nil {
		return x.Prereq
	}
	return ""
}

func (x *SkillInfo) GetWeaponReq() string {
	if x != nil {
		return x.WeaponReq
	}
	return ""
}

func (x *SkillInfo) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *SkillInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SkillInfo) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

func (x *SkillInfo) GetUnlockLevel() int32 {
	if x != nil {
		return x.UnlockLevel
	}
	return 0
}

func (x *SkillInfo) GetUsage() int32 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *SkillInfo) GetUsageToNext() int32 {
	if x != nil {
		return x.UsageToNext
	}
	return 0
}

func (x *SkillInfo) GetCastTimeMs() int32 {
	if x != nil {
		return x.CastTimeMs
	}
	return 0
}

func (x *SkillInfo) GetWorldOnly() bool {
	if x != nil {
		return x.WorldOnly
	}
	return false
}

type JobProgressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Abbr          string                 `protobuf:"bytes,3,opt,name=abbr,proto3" json:"abbr,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Xp            int32                  `protobuf:"varint,6,opt,name=xp,proto3" json:"xp,omitempty"`
	MaxXp         int32                  `protobuf:"varint,7,opt,name=max_xp,json=maxXp,proto3" json:"max_xp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobProgressInfo) Reset() {
	*x = JobProgressInfo{}
	mi := &file_fantasy_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgressInfo) ProtoMessage() {}

func (x *JobProgressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgressInfo.ProtoReflect.Descriptor instead.
func (*JobProgressInfo) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *JobProgressInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobProgressInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobProgressInfo) GetAbbr() string {
	if x != nil {
		return x.Abbr
	}
	return ""
}

func (x *JobProgressInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *JobProgressInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *JobProgressInfo) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *JobProgressInfo) GetMaxXp() int32 {
	if x != nil {
		return x.MaxXp
	}
	return 0
}

type StatBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hp            int32                  `protobuf:"varint,1,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            int32                  `protobuf:"varint,2,opt,name=mp,proto3" json:"mp,omitempty"`
	Str           int32                  `protobuf:"varint,3,opt,name=str,proto3" json:"str,omitempty"`
	Mag           int32                  `protobuf:"varint,4,opt,name=mag,proto3" json:"mag,omitempty"`
	Agi           int32                  `protobuf:"varint,5,opt,name=agi,proto3" json:"agi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBlock) Reset() {
	*x = StatBlock{}
	mi := &file_fantasy_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBlock) ProtoMessage() {}

func (x *StatBlock) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBlock.ProtoReflect.Descriptor instead.
func (*StatBlock) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *StatBlock) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *StatBlock) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *StatBlock) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *StatBlock) GetMag() int32 {
	if x != nil {
		return x.Mag
	}
	return 0
}

func (x *StatBlock) GetAgi() int32 {
	if x != nil {
		return x.Agi
	}
	return 0
}

type HotbarBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotbarBinding) Reset() {
	*x = HotbarBinding{}
	mi := &file_fantasy_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotbarBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotbarBinding) ProtoMessage() {}

func (x *HotbarBinding) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotbarBinding.ProtoReflect.Descriptor instead.
func (*HotbarBinding) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *HotbarBinding) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HotbarBinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VisitedSavePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MapName       string                 `protobuf:"bytes,3,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	Home          bool                   `protobuf:"varint,4,opt,name=home,proto3" json:"home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitedSavePoint) Reset() {
	*x = VisitedSavePoint{}
	mi := &file_fantasy_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitedSavePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitedSavePoint) ProtoMessage() {}

func (x *VisitedSavePoint) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitedSavePoint.ProtoReflect.Descriptor instead.
func (*VisitedSavePoint) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *VisitedSavePoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VisitedSavePoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VisitedSavePoint) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *VisitedSavePoint) GetHome() bool {
	if x != nil {
		return x.Home
	}
	return false
}

type PetRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecord) Reset() {
	*x = PetRecord{}
	mi := &file_fantasy_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecord) ProtoMessage() {}

func (x *PetRecord) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecord.ProtoReflect.Descriptor instead.
func (*PetRecord) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *PetRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PetRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PetRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetRecord) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type ProfileInfo struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32                     `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Xp                   int32                     `protobuf:"varint,3,opt,name=xp,proto3" json:"xp,omitempty"`
	MaxXp                int32                     `protobuf:"varint,4,opt,name=max_xp,json=maxXp,proto3" json:"max_xp,omitempty"`
	Race                 string                    `protobuf:"bytes,5,opt,name=race,proto3" json:"race,omitempty"`
	MainJob              string                    `protobuf:"bytes,6,opt,name=main_job,json=mainJob,proto3" json:"main_job,omitempty"`
	SubJob               string                    `protobuf:"bytes,7,opt,name=sub_job,json=subJob,proto3" json:"sub_job,omitempty"`
	SubjobUnlockLevel    int32                     `protobuf:"varint,8,opt,name=subjob_unlock_level,json=subjobUnlockLevel,proto3" json:"subjob_unlock_level,omitempty"`
	UnlockedJobs         []string                  `protobuf:"bytes,9,rep,name=unlocked_jobs,json=unlockedJobs,proto3" json:"unlocked_jobs,omitempty"`
	Appearance           *CharacterAppearance      `protobuf:"bytes,10,opt,name=appearance,proto3" json:"appearance,omitempty"`
	Jobs                 []*JobProgressInfo        `protobuf:"bytes,11,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Stats                *StatBlock                `protobuf:"bytes,12,opt,name=stats,proto3" json:"stats,omitempty"`
	Inventory            []*Item                   `protobuf:"bytes,13,rep,name=inventory,proto3" json:"inventory,omitempty"`
	Equipped             map[string]string         `protobuf:"bytes,14,rep,name=equipped,proto3" json:"equipped,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Hotbar               map[string]*HotbarBinding `protobuf:"bytes,15,rep,name=hotbar,proto3" json:"hotbar,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Skills               []*SkillInfo              `protobuf:"bytes,16,rep,name=skills,proto3" json:"skills,omitempty"`
	Friends              []string                  `protobuf:"bytes,17,rep,name=friends,proto3" json:"friends,omitempty"`
	SavePointId          string                    `protobuf:"bytes,18,opt,name=save_point_id,json=savePointId,proto3" json:"save_point_id,omitempty"`
	SavePointName        string                    `protobuf:"bytes,19,opt,name=save_point_name,json=savePointName,proto3" json:"save_point_name,omitempty"`
	VisitedSavePoints    []*VisitedSavePoint       `protobuf:"bytes,20,rep,name=visited_save_points,json=visitedSavePoints,proto3" json:"visited_save_points,omitempty"`
	Keybinds             map[string]string         `protobuf:"bytes,21,rep,name=keybinds,proto3" json:"keybinds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CampSkin             string                    `protobuf:"bytes,22,opt,name=camp_skin,json=campSkin,proto3" json:"camp_skin,omitempty"`
	HouseStorage         []*Item                   `protobuf:"bytes,23,rep,name=house_storage,json=houseStorage,proto3" json:"house_storage,omitempty"`
	HouseStorageCapacity int32                     `protobuf:"varint,24,opt,name=house_storage_capacity,json=houseStorageCapacity,proto3" json:"house_storage_capacity,omitempty"`
	Pets                 []*PetRecord              `protobuf:"bytes,25,rep,name=pets,proto3" json:"pets,omitempty"`
	FollowPetId          string                    `protobuf:"bytes,26,opt,name=follow_pet_id,json=followPetId,proto3" json:"follow_pet_id,omitempty"`
	BattlePetId          string                    `protobuf:"bytes,27,opt,name=battle_pet_id,json=battlePetId,proto3" json:"battle_pet_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProfileInfo) Reset() {
	*x = ProfileInfo{}
	mi := &file_fantasy_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileInfo) ProtoMessage() {}

func (x *ProfileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileInfo.ProtoReflect.Descriptor instead.
func (*ProfileInfo) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *ProfileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ProfileInfo) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *ProfileInfo) GetMaxXp() int32 {
	if x != nil {
		return x.MaxXp
	}
	return 0
}

func (x *ProfileInfo) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

func (x *ProfileInfo) GetMainJob() string {
	if x != nil {
		return x.MainJob
	}
	return ""
}

func (x *ProfileInfo) GetSubJob() string {
	if x != nil {
		return x.SubJob
	}
	return ""
}

func (x *ProfileInfo) GetSubjobUnlockLevel() int32 {
	if x != nil {
		return x.SubjobUnlockLevel
	}
	return 0
}

func (x *ProfileInfo) GetUnlockedJobs() []string {
	if x != nil {
		return x.UnlockedJobs
	}
	return nil
}

func (x *ProfileInfo) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *ProfileInfo) GetJobs() []*JobProgressInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ProfileInfo) GetStats() *StatBlock {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ProfileInfo) GetInventory() []*Item {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *ProfileInfo) GetEquipped() map[string]string {
	if x != nil {
		return x.Equipped
	}
	return nil
}

func (x *ProfileInfo) GetHotbar() map[string]*HotbarBinding {
	if x != nil {
		return x.Hotbar
	}
	return nil
}

func (x *ProfileInfo) GetSkills() []*SkillInfo {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ProfileInfo) GetFriends() []string {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *ProfileInfo) GetSavePointId() string {
	if x != nil {
		return x.SavePointId
	}
	return ""
}

func (x *ProfileInfo) GetSavePointName() string {
	if x != nil {
		return x.SavePointName
	}
	return ""
}

func (x *ProfileInfo) GetVisitedSavePoints() []*VisitedSavePoint {
	if x != nil {
		return x.VisitedSavePoints
	}
	return nil
}

func (x *ProfileInfo) GetKeybinds() map[string]string {
	if x != nil {
		return x.Keybinds
	}
	return nil
}

func (x *ProfileInfo) GetCampSkin() string {
	if x != nil {
		return x.CampSkin
	}
	return ""
}

func (x *ProfileInfo) GetHouseStorage() []*Item {
	if x != nil {
		return x.HouseStorage
	}
	return nil
}

func (x *ProfileInfo) GetHouseStorageCapacity() int32 {
	if x != nil {
		return x.HouseStorageCapacity
	}
	return 0
}

func (x *ProfileInfo) GetPets() []*PetRecord {
	if x != nil {
		return x.Pets
	}
	return nil
}

func (x *ProfileInfo) GetFollowPetId() string {
	if x != nil {
		return x.FollowPetId
	}
	return ""
}

func (x *ProfileInfo) GetBattlePetId() string {
	if x != nil {
		return x.BattlePetId
	}
	return ""
}

type OverworldMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tile          int32                  `protobuf:"varint,1,opt,name=tile,proto3" json:"tile,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cells         string                 `protobuf:"bytes,4,opt,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverworldMap) Reset() {
	*x = OverworldMap{}
	mi := &file_fantasy_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverworldMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverworldMap) ProtoMessage() {}

func (x *OverworldMap) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverworldMap.ProtoReflect.Descriptor instead.
func (*OverworldMap) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *OverworldMap) GetTile() int32 {
	if x != nil {
		return x.Tile
	}
	return 0
}

func (x *OverworldMap) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *OverworldMap) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *OverworldMap) GetCells() string {
	if x != nil {
		return x.Cells
	}
	return ""
}

type MapTerrainLayers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ground        []int32                `protobuf:"varint,1,rep,packed,name=ground,proto3" json:"ground,omitempty"`
	Collision     []int32                `protobuf:"varint,2,rep,packed,name=collision,proto3" json:"collision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapTerrainLayers) Reset() {
	*x = MapTerrainLayers{}
	mi := &file_fantasy_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapTerrainLayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTerrainLayers) ProtoMessage() {}

func (x *MapTerrainLayers) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTerrainLayers.ProtoReflect.Descriptor instead.
func (*MapTerrainLayers) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *MapTerrainLayers) GetGround() []int32 {
	if x != nil {
		return x.Ground
	}
	return nil
}

func (x *MapTerrainLayers) GetCollision() []int32 {
	if x != nil {
		return x.Collision
	}
	return nil
}

type MapTileOverrides struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Layers        *structpb.Struct       `protobuf:"bytes,2,opt,name=layers,proto3" json:"layers,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapTileOverrides) Reset() {
	*x = MapTileOverrides{}
	mi := &file_fantasy_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapTileOverrides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTileOverrides) ProtoMessage() {}

func (x *MapTileOverrides) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTileOverrides.ProtoReflect.Descriptor instead.
func (*MapTileOverrides) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *MapTileOverrides) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapTileOverrides) GetLayers() *structpb.Struct {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *MapTileOverrides) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MapPortal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	W             float64                `protobuf:"fixed64,3,opt,name=w,proto3" json:"w,omitempty"`
	H             float64                `protobuf:"fixed64,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapPortal) Reset() {
	*x = MapPortal{}
	mi := &file_fantasy_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapPortal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPortal) ProtoMessage() {}

func (x *MapPortal) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPortal.ProtoReflect.Descriptor instead.
func (*MapPortal) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{13}
}

func (x *MapPortal) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapPortal) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapPortal) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *MapPortal) GetH() float64 {
	if x != nil {
		return x.H
	}
	return 0
}

type MapSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Overworld     *OverworldMap          `protobuf:"bytes,6,opt,name=overworld,proto3" json:"overworld,omitempty"`
	TiledMap      string                 `protobuf:"bytes,7,opt,name=tiled_map,json=tiledMap,proto3" json:"tiled_map,omitempty"`
	Portals       []*MapPortal           `protobuf:"bytes,8,rep,name=portals,proto3" json:"portals,omitempty"`
	TileOverrides *MapTileOverrides      `protobuf:"bytes,9,opt,name=tile_overrides,json=tileOverrides,proto3" json:"tile_overrides,omitempty"`
	TerrainLayers *MapTerrainLayers      `protobuf:"bytes,10,opt,name=terrain_layers,json=terrainLayers,proto3" json:"terrain_layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSnapshot) Reset() {
	*x = MapSnapshot{}
	mi := &file_fantasy_v1_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSnapshot) ProtoMessage() {}

func (x *MapSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSnapshot.ProtoReflect.Descriptor instead.
func (*MapSnapshot) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{14}
}

func (x *MapSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MapSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapSnapshot) GetOverworld() *OverworldMap {
	if x != nil {
		return x.Overworld
	}
	return nil
}

func (x *MapSnapshot) GetTiledMap() string {
	if x != nil {
		return x.TiledMap
	}
	return ""
}

func (x *MapSnapshot) GetPortals() []*MapPortal {
	if x != nil {
		return x.Portals
	}
	return nil
}

func (x *MapSnapshot) GetTileOverrides() *MapTileOverrides {
	if x != nil {
		return x.TileOverrides
	}
	return nil
}

func (x *MapSnapshot) GetTerrainLayers() *MapTerrainLayers {
	if x != nil {
		return x.TerrainLayers
	}
	return nil
}

// WorldEntity is the unified snapshot for every world inhabitant: players,
// NPCs, and pets. kind selects the entity class ("player" | "npc" | "pet");
// fields that don't apply to a kind stay at their proto defaults.
type WorldEntity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind            string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Sprite          string                 `protobuf:"bytes,4,opt,name=sprite,proto3" json:"sprite,omitempty"` // enemy key / pet kind / player race
	OwnerId         string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Level           int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	X               float64                `protobuf:"fixed64,7,opt,name=x,proto3" json:"x,omitempty"`
	Y               float64                `protobuf:"fixed64,8,opt,name=y,proto3" json:"y,omitempty"`
	Facing          float64                `protobuf:"fixed64,9,opt,name=facing,proto3" json:"facing,omitempty"` // Y-axis yaw radians
	Hp              int32                  `protobuf:"varint,10,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp           int32                  `protobuf:"varint,11,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Mp              int32                  `protobuf:"varint,12,opt,name=mp,proto3" json:"mp,omitempty"`
	MaxMp           int32                  `protobuf:"varint,13,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	Stamina         float64                `protobuf:"fixed64,14,opt,name=stamina,proto3" json:"stamina,omitempty"`
	Alive           bool                   `protobuf:"varint,15,opt,name=alive,proto3" json:"alive,omitempty"`
	Engaged         bool                   `protobuf:"varint,16,opt,name=engaged,proto3" json:"engaged,omitempty"` // in combat
	IsAlly          bool                   `protobuf:"varint,17,opt,name=is_ally,json=isAlly,proto3" json:"is_ally,omitempty"`
	TargetId        string                 `protobuf:"bytes,18,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Statuses        []*StatusSnapshot      `protobuf:"bytes,19,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Capturable      bool                   `protobuf:"varint,20,opt,name=capturable,proto3" json:"capturable,omitempty"`
	SkillAtb        float64                `protobuf:"fixed64,21,opt,name=skill_atb,json=skillAtb,proto3" json:"skill_atb,omitempty"`
	HasQueuedAction bool                   `protobuf:"varint,22,opt,name=has_queued_action,json=hasQueuedAction,proto3" json:"has_queued_action,omitempty"`
	CastingSkillId  string                 `protobuf:"bytes,23,opt,name=casting_skill_id,json=castingSkillId,proto3" json:"casting_skill_id,omitempty"`
	CastTargetId    string                 `protobuf:"bytes,24,opt,name=cast_target_id,json=castTargetId,proto3" json:"cast_target_id,omitempty"`
	CastProgress    float64                `protobuf:"fixed64,25,opt,name=cast_progress,json=castProgress,proto3" json:"cast_progress,omitempty"`
	CastTimeMs      int32                  `protobuf:"varint,26,opt,name=cast_time_ms,json=castTimeMs,proto3" json:"cast_time_ms,omitempty"`
	CastEndsAt      int64                  `protobuf:"varint,27,opt,name=cast_ends_at,json=castEndsAt,proto3" json:"cast_ends_at,omitempty"` // unix millis
	// Player presence extras.
	Weapon        string               `protobuf:"bytes,28,opt,name=weapon,proto3" json:"weapon,omitempty"`
	MainJob       string               `protobuf:"bytes,29,opt,name=main_job,json=mainJob,proto3" json:"main_job,omitempty"`
	SubJob        string               `protobuf:"bytes,30,opt,name=sub_job,json=subJob,proto3" json:"sub_job,omitempty"`
	Appearance    *CharacterAppearance `protobuf:"bytes,31,opt,name=appearance,proto3" json:"appearance,omitempty"`
	ImmuneUntil   int64                `protobuf:"varint,32,opt,name=immune_until,json=immuneUntil,proto3" json:"immune_until,omitempty"` // unix millis; collision/search blocked
	InHouse       bool                 `protobuf:"varint,33,opt,name=in_house,json=inHouse,proto3" json:"in_house,omitempty"`
	HouseOwner    string               `protobuf:"bytes,34,opt,name=house_owner,json=houseOwner,proto3" json:"house_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldEntity) Reset() {
	*x = WorldEntity{}
	mi := &file_fantasy_v1_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldEntity) ProtoMessage() {}

func (x *WorldEntity) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldEntity.ProtoReflect.Descriptor instead.
func (*WorldEntity) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{15}
}

func (x *WorldEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorldEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorldEntity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorldEntity) GetSprite() string {
	if x != nil {
		return x.Sprite
	}
	return ""
}

func (x *WorldEntity) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *WorldEntity) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *WorldEntity) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WorldEntity) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WorldEntity) GetFacing() float64 {
	if x != nil {
		return x.Facing
	}
	return 0
}

func (x *WorldEntity) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *WorldEntity) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *WorldEntity) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *WorldEntity) GetMaxMp() int32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *WorldEntity) GetStamina() float64 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WorldEntity) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *WorldEntity) GetEngaged() bool {
	if x != nil {
		return x.Engaged
	}
	return false
}

func (x *WorldEntity) GetIsAlly() bool {
	if x != nil {
		return x.IsAlly
	}
	return false
}

func (x *WorldEntity) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *WorldEntity) GetStatuses() []*StatusSnapshot {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *WorldEntity) GetCapturable() bool {
	if x != nil {
		return x.Capturable
	}
	return false
}

func (x *WorldEntity) GetSkillAtb() float64 {
	if x != nil {
		return x.SkillAtb
	}
	return 0
}

func (x *WorldEntity) GetHasQueuedAction() bool {
	if x != nil {
		return x.HasQueuedAction
	}
	return false
}

func (x *WorldEntity) GetCastingSkillId() string {
	if x != nil {
		return x.CastingSkillId
	}
	return ""
}

func (x *WorldEntity) GetCastTargetId() string {
	if x != nil {
		return x.CastTargetId
	}
	return ""
}

func (x *WorldEntity) GetCastProgress() float64 {
	if x != nil {
		return x.CastProgress
	}
	return 0
}

func (x *WorldEntity) GetCastTimeMs() int32 {
	if x != nil {
		return x.CastTimeMs
	}
	return 0
}

func (x *WorldEntity) GetCastEndsAt() int64 {
	if x != nil {
		return x.CastEndsAt
	}
	return 0
}

func (x *WorldEntity) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *WorldEntity) GetMainJob() string {
	if x != nil {
		return x.MainJob
	}
	return ""
}

func (x *WorldEntity) GetSubJob() string {
	if x != nil {
		return x.SubJob
	}
	return ""
}

func (x *WorldEntity) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

func (x *WorldEntity) GetImmuneUntil() int64 {
	if x != nil {
		return x.ImmuneUntil
	}
	return 0
}

func (x *WorldEntity) GetInHouse() bool {
	if x != nil {
		return x.InHouse
	}
	return false
}

func (x *WorldEntity) GetHouseOwner() string {
	if x != nil {
		return x.HouseOwner
	}
	return ""
}

type WorldCamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Skin          string                 `protobuf:"bytes,5,opt,name=skin,proto3" json:"skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldCamp) Reset() {
	*x = WorldCamp{}
	mi := &file_fantasy_v1_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldCamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldCamp) ProtoMessage() {}

func (x *WorldCamp) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldCamp.ProtoReflect.Descriptor instead.
func (*WorldCamp) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{16}
}

func (x *WorldCamp) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *WorldCamp) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *WorldCamp) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WorldCamp) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WorldCamp) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

type HouseFurniture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Item          *Item                  `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseFurniture) Reset() {
	*x = HouseFurniture{}
	mi := &file_fantasy_v1_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseFurniture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseFurniture) ProtoMessage() {}

func (x *HouseFurniture) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseFurniture.ProtoReflect.Descriptor instead.
func (*HouseFurniture) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{17}
}

func (x *HouseFurniture) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HouseFurniture) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *HouseFurniture) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *HouseFurniture) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HouseFurniture) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type HousePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Facing        float64                `protobuf:"fixed64,5,opt,name=facing,proto3" json:"facing,omitempty"` // Y-axis yaw radians
	Owner         bool                   `protobuf:"varint,6,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HousePlayer) Reset() {
	*x = HousePlayer{}
	mi := &file_fantasy_v1_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HousePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HousePlayer) ProtoMessage() {}

func (x *HousePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HousePlayer.ProtoReflect.Descriptor instead.
func (*HousePlayer) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{18}
}

func (x *HousePlayer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HousePlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HousePlayer) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HousePlayer) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *HousePlayer) GetFacing() float64 {
	if x != nil {
		return x.Facing
	}
	return 0
}

func (x *HousePlayer) GetOwner() bool {
	if x != nil {
		return x.Owner
	}
	return false
}

type HousePOI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	X             float64                `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HousePOI) Reset() {
	*x = HousePOI{}
	mi := &file_fantasy_v1_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HousePOI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HousePOI) ProtoMessage() {}

func (x *HousePOI) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HousePOI.ProtoReflect.Descriptor instead.
func (*HousePOI) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{19}
}

func (x *HousePOI) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HousePOI) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HousePOI) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HousePOI) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HousePOI) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SavePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePoint) Reset() {
	*x = SavePoint{}
	mi := &file_fantasy_v1_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePoint) ProtoMessage() {}

func (x *SavePoint) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePoint.ProtoReflect.Descriptor instead.
func (*SavePoint) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{20}
}

func (x *SavePoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SavePoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SavePoint) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SavePoint) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type JobChanger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobChanger) Reset() {
	*x = JobChanger{}
	mi := &file_fantasy_v1_common_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobChanger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobChanger) ProtoMessage() {}

func (x *JobChanger) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobChanger.ProtoReflect.Descriptor instead.
func (*JobChanger) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{21}
}

func (x *JobChanger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobChanger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobChanger) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *JobChanger) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerReward struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Xp              int32                  `protobuf:"varint,2,opt,name=xp,proto3" json:"xp,omitempty"`
	SubXp           int32                  `protobuf:"varint,3,opt,name=sub_xp,json=subXp,proto3" json:"sub_xp,omitempty"`
	LevelsGained    int32                  `protobuf:"varint,4,opt,name=levels_gained,json=levelsGained,proto3" json:"levels_gained,omitempty"`
	SubLevelsGained int32                  `protobuf:"varint,5,opt,name=sub_levels_gained,json=subLevelsGained,proto3" json:"sub_levels_gained,omitempty"`
	NewLevel        int32                  `protobuf:"varint,6,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	NewXp           int32                  `protobuf:"varint,7,opt,name=new_xp,json=newXp,proto3" json:"new_xp,omitempty"`
	MaxXp           int32                  `protobuf:"varint,8,opt,name=max_xp,json=maxXp,proto3" json:"max_xp,omitempty"`
	SubNewLevel     int32                  `protobuf:"varint,9,opt,name=sub_new_level,json=subNewLevel,proto3" json:"sub_new_level,omitempty"`
	SubNewXp        int32                  `protobuf:"varint,10,opt,name=sub_new_xp,json=subNewXp,proto3" json:"sub_new_xp,omitempty"`
	SubMaxXp        int32                  `protobuf:"varint,11,opt,name=sub_max_xp,json=subMaxXp,proto3" json:"sub_max_xp,omitempty"`
	Loot            []*Item                `protobuf:"bytes,12,rep,name=loot,proto3" json:"loot,omitempty"`
	Passive         bool                   `protobuf:"varint,13,opt,name=passive,proto3" json:"passive,omitempty"`
	PartyBonus      bool                   `protobuf:"varint,14,opt,name=party_bonus,json=partyBonus,proto3" json:"party_bonus,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerReward) Reset() {
	*x = PlayerReward{}
	mi := &file_fantasy_v1_common_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReward) ProtoMessage() {}

func (x *PlayerReward) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReward.ProtoReflect.Descriptor instead.
func (*PlayerReward) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerReward) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerReward) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *PlayerReward) GetSubXp() int32 {
	if x != nil {
		return x.SubXp
	}
	return 0
}

func (x *PlayerReward) GetLevelsGained() int32 {
	if x != nil {
		return x.LevelsGained
	}
	return 0
}

func (x *PlayerReward) GetSubLevelsGained() int32 {
	if x != nil {
		return x.SubLevelsGained
	}
	return 0
}

func (x *PlayerReward) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *PlayerReward) GetNewXp() int32 {
	if x != nil {
		return x.NewXp
	}
	return 0
}

func (x *PlayerReward) GetMaxXp() int32 {
	if x != nil {
		return x.MaxXp
	}
	return 0
}

func (x *PlayerReward) GetSubNewLevel() int32 {
	if x != nil {
		return x.SubNewLevel
	}
	return 0
}

func (x *PlayerReward) GetSubNewXp() int32 {
	if x != nil {
		return x.SubNewXp
	}
	return 0
}

func (x *PlayerReward) GetSubMaxXp() int32 {
	if x != nil {
		return x.SubMaxXp
	}
	return 0
}

func (x *PlayerReward) GetLoot() []*Item {
	if x != nil {
		return x.Loot
	}
	return nil
}

func (x *PlayerReward) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *PlayerReward) GetPartyBonus() bool {
	if x != nil {
		return x.PartyBonus
	}
	return false
}

type FriendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Weapon        string                 `protobuf:"bytes,4,opt,name=weapon,proto3" json:"weapon,omitempty"`
	InCombat      bool                   `protobuf:"varint,5,opt,name=in_combat,json=inCombat,proto3" json:"in_combat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	mi := &file_fantasy_v1_common_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{23}
}

func (x *FriendInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FriendInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *FriendInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FriendInfo) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *FriendInfo) GetInCombat() bool {
	if x != nil {
		return x.InCombat
	}
	return false
}

type PartyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Weapon        string                 `protobuf:"bytes,4,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Leader        bool                   `protobuf:"varint,5,opt,name=leader,proto3" json:"leader,omitempty"`
	InCombat      bool                   `protobuf:"varint,6,opt,name=in_combat,json=inCombat,proto3" json:"in_combat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyMember) Reset() {
	*x = PartyMember{}
	mi := &file_fantasy_v1_common_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMember) ProtoMessage() {}

func (x *PartyMember) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMember.ProtoReflect.Descriptor instead.
func (*PartyMember) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{24}
}

func (x *PartyMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartyMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartyMember) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PartyMember) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *PartyMember) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *PartyMember) GetInCombat() bool {
	if x != nil {
		return x.InCombat
	}
	return false
}

type PartyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Members       []*PartyMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInfo) Reset() {
	*x = PartyInfo{}
	mi := &file_fantasy_v1_common_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInfo) ProtoMessage() {}

func (x *PartyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_common_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInfo.ProtoReflect.Descriptor instead.
func (*PartyInfo) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_common_proto_rawDescGZIP(), []int{25}
}

func (x *PartyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartyInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *PartyInfo) GetMembers() []*PartyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_fantasy_v1_common_proto protoreflect.FileDescriptor

const file_fantasy_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17fantasy/v1/common.proto\x12\n" +
	"fantasy.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe2\x01\n" +
	"\x13CharacterAppearance\x12\x12\n" +
	"\x04skin\x18\x01 \x01(\tR\x04skin\x12\x12\n" +
	"\x04face\x18\x02 \x01(\tR\x04face\x12\x12\n" +
	"\x04hair\x18\x03 \x01(\tR\x04hair\x12\x1d\n" +
	"\n" +
	"hair_color\x18\x04 \x01(\tR\thairColor\x12\x14\n" +
	"\x05cloth\x18\x05 \x01(\tR\x05cloth\x12\x1f\n" +
	"\vcloth_color\x18\x06 \x01(\tR\n" +
	"clothColor\x12\x16\n" +
	"\x06weapon\x18\a \x01(\tR\x06weapon\x12!\n" +
	"\fweapon_color\x18\b \x01(\tR\vweaponColor\"\xb3\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\tR\x04slot\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"consumable\x18\x06 \x01(\tR\n" +
	"consumable\x12\x16\n" +
	"\x06rarity\x18\a \x01(\tR\x06rarity\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12\x10\n" +
	"\x03qty\x18\t \x01(\x05R\x03qty\x121\n" +
	"\x05stats\x18\n" +
	" \x03(\v2\x1b.fantasy.v1.Item.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"y\n" +
	"\x0eStatusSnapshot\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\apotency\x18\x02 \x01(\x01R\apotency\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\x12\x1b\n" +
	"\tshield_hp\x18\x04 \x01(\x05R\bshieldHp\"\xe8\x03\n" +
	"\tSkillInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\amp_cost\x18\x03 \x01(\x05R\x06mpCost\x12\x14\n" +
	"\x05heals\x18\x04 \x01(\bR\x05heals\x12\x14\n" +
	"\x05buffs\x18\x05 \x01(\bR\x05buffs\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x10\n" +
	"\x03job\x18\a \x01(\tR\x03job\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x16\n" +
	"\x06prereq\x18\t \x01(\tR\x06prereq\x12\x1d\n" +
	"\n" +
	"weapon_req\x18\n" +
	" \x01(\tR\tweaponReq\x12\x1a\n" +
	"\bunlocked\x18\v \x01(\bR\bunlocked\x12\x14\n" +
	"\x05level\x18\f \x01(\x05R\x05level\x12\x1b\n" +
	"\tmax_level\x18\r \x01(\x05R\bmaxLevel\x12!\n" +
	"\funlock_level\x18\x0e \x01(\x05R\vunlockLevel\x12\x14\n" +
	"\x05usage\x18\x0f \x01(\x05R\x05usage\x12\"\n" +
	"\rusage_to_next\x18\x10 \x01(\x05R\vusageToNext\x12 \n" +
	"\fcast_time_ms\x18\x11 \x01(\x05R\n" +
	"castTimeMs\x12\x1d\n" +
	"\n" +
	"world_only\x18\x12 \x01(\bR\tworldOnly\"\xa2\x01\n" +
	"\x0fJobProgressInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04abbr\x18\x03 \x01(\tR\x04abbr\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x0e\n" +
	"\x02xp\x18\x06 \x01(\x05R\x02xp\x12\x15\n" +
	"\x06max_xp\x18\a \x01(\x05R\x05maxXp\"a\n" +
	"\tStatBlock\x12\x0e\n" +
	"\x02hp\x18\x01 \x01(\x05R\x02hp\x12\x0e\n" +
	"\x02mp\x18\x02 \x01(\x05R\x02mp\x12\x10\n" +
	"\x03str\x18\x03 \x01(\x05R\x03str\x12\x10\n" +
	"\x03mag\x18\x04 \x01(\x05R\x03mag\x12\x10\n" +
	"\x03agi\x18\x05 \x01(\x05R\x03agi\"3\n" +
	"\rHotbarBinding\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"e\n" +
	"\x10VisitedSavePoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bmap_name\x18\x03 \x01(\tR\amapName\x12\x12\n" +
	"\x04home\x18\x04 \x01(\bR\x04home\"Y\n" +
	"\tPetRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\"\xc3\n" +
	"\n" +
	"\vProfileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x0e\n" +
	"\x02xp\x18\x03 \x01(\x05R\x02xp\x12\x15\n" +
	"\x06max_xp\x18\x04 \x01(\x05R\x05maxXp\x12\x12\n" +
	"\x04race\x18\x05 \x01(\tR\x04race\x12\x19\n" +
	"\bmain_job\x18\x06 \x01(\tR\amainJob\x12\x17\n" +
	"\asub_job\x18\a \x01(\tR\x06subJob\x12.\n" +
	"\x13subjob_unlock_level\x18\b \x01(\x05R\x11subjobUnlockLevel\x12#\n" +
	"\runlocked_jobs\x18\t \x03(\tR\funlockedJobs\x12?\n" +
	"\n" +
	"appearance\x18\n" +
	" \x01(\v2\x1f.fantasy.v1.CharacterAppearanceR\n" +
	"appearance\x12/\n" +
	"\x04jobs\x18\v \x03(\v2\x1b.fantasy.v1.JobProgressInfoR\x04jobs\x12+\n" +
	"\x05stats\x18\f \x01(\v2\x15.fantasy.v1.StatBlockR\x05stats\x12.\n" +
	"\tinventory\x18\r \x03(\v2\x10.fantasy.v1.ItemR\tinventory\x12A\n" +
	"\bequipped\x18\x0e \x03(\v2%.fantasy.v1.ProfileInfo.EquippedEntryR\bequipped\x12;\n" +
	"\x06hotbar\x18\x0f \x03(\v2#.fantasy.v1.ProfileInfo.HotbarEntryR\x06hotbar\x12-\n" +
	"\x06skills\x18\x10 \x03(\v2\x15.fantasy.v1.SkillInfoR\x06skills\x12\x18\n" +
	"\afriends\x18\x11 \x03(\tR\afriends\x12\"\n" +
	"\rsave_point_id\x18\x12 \x01(\tR\vsavePointId\x12&\n" +
	"\x0fsave_point_name\x18\x13 \x01(\tR\rsavePointName\x12L\n" +
	"\x13visited_save_points\x18\x14 \x03(\v2\x1c.fantasy.v1.VisitedSavePointR\x11visitedSavePoints\x12A\n" +
	"\bkeybinds\x18\x15 \x03(\v2%.fantasy.v1.ProfileInfo.KeybindsEntryR\bkeybinds\x12\x1b\n" +
	"\tcamp_skin\x18\x16 \x01(\tR\bcampSkin\x125\n" +
	"\rhouse_storage\x18\x17 \x03(\v2\x10.fantasy.v1.ItemR\fhouseStorage\x124\n" +
	"\x16house_storage_capacity\x18\x18 \x01(\x05R\x14houseStorageCapacity\x12)\n" +
	"\x04pets\x18\x19 \x03(\v2\x15.fantasy.v1.PetRecordR\x04pets\x12\"\n" +
	"\rfollow_pet_id\x18\x1a \x01(\tR\vfollowPetId\x12\"\n" +
	"\rbattle_pet_id\x18\x1b \x01(\tR\vbattlePetId\x1a;\n" +
	"\rEquippedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aT\n" +
	"\vHotbarEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.fantasy.v1.HotbarBindingR\x05value:\x028\x01\x1a;\n" +
	"\rKeybindsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x1c\x10\x1d\"`\n" +
	"\fOverworldMap\x12\x12\n" +
	"\x04tile\x18\x01 \x01(\x05R\x04tile\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12\x14\n" +
	"\x05cells\x18\x04 \x01(\tR\x05cells\"H\n" +
	"\x10MapTerrainLayers\x12\x16\n" +
	"\x06ground\x18\x01 \x03(\x05R\x06ground\x12\x1c\n" +
	"\tcollision\x18\x02 \x03(\x05R\tcollision\"y\n" +
	"\x10MapTileOverrides\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12/\n" +
	"\x06layers\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06layers\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"C\n" +
	"\tMapPortal\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x01R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x01R\x01h\"\xc1\x02\n" +
	"\vMapSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\toverworld\x18\x06 \x01(\v2\x18.fantasy.v1.OverworldMapR\toverworld\x12\x1b\n" +
	"\ttiled_map\x18\a \x01(\tR\btiledMap\x12/\n" +
	"\aportals\x18\b \x03(\v2\x15.fantasy.v1.MapPortalR\aportals\x12C\n" +
	"\x0etile_overrides\x18\t \x01(\v2\x1c.fantasy.v1.MapTileOverridesR\rtileOverrides\x12C\n" +
	"\x0eterrain_layers\x18\n" +
	" \x01(\v2\x1c.fantasy.v1.MapTerrainLayersR\rterrainLayers\"\xd6\a\n" +
	"\vWorldEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06sprite\x18\x04 \x01(\tR\x06sprite\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\f\n" +
	"\x01x\x18\a \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\b \x01(\x01R\x01y\x12\x16\n" +
	"\x06facing\x18\t \x01(\x01R\x06facing\x12\x0e\n" +
	"\x02hp\x18\n" +
	" \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\v \x01(\x05R\x05maxHp\x12\x0e\n" +
	"\x02mp\x18\f \x01(\x05R\x02mp\x12\x15\n" +
	"\x06max_mp\x18\r \x01(\x05R\x05maxMp\x12\x18\n" +
	"\astamina\x18\x0e \x01(\x01R\astamina\x12\x14\n" +
	"\x05alive\x18\x0f \x01(\bR\x05alive\x12\x18\n" +
	"\aengaged\x18\x10 \x01(\bR\aengaged\x12\x17\n" +
	"\ais_ally\x18\x11 \x01(\bR\x06isAlly\x12\x1b\n" +
	"\ttarget_id\x18\x12 \x01(\tR\btargetId\x126\n" +
	"\bstatuses\x18\x13 \x03(\v2\x1a.fantasy.v1.StatusSnapshotR\bstatuses\x12\x1e\n" +
	"\n" +
	"capturable\x18\x14 \x01(\bR\n" +
	"capturable\x12\x1b\n" +
	"\tskill_atb\x18\x15 \x01(\x01R\bskillAtb\x12*\n" +
	"\x11has_queued_action\x18\x16 \x01(\bR\x0fhasQueuedAction\x12(\n" +
	"\x10casting_skill_id\x18\x17 \x01(\tR\x0ecastingSkillId\x12$\n" +
	"\x0ecast_target_id\x18\x18 \x01(\tR\fcastTargetId\x12#\n" +
	"\rcast_progress\x18\x19 \x01(\x01R\fcastProgress\x12 \n" +
	"\fcast_time_ms\x18\x1a \x01(\x05R\n" +
	"castTimeMs\x12 \n" +
	"\fcast_ends_at\x18\x1b \x01(\x03R\n" +
	"castEndsAt\x12\x16\n" +
	"\x06weapon\x18\x1c \x01(\tR\x06weapon\x12\x19\n" +
	"\bmain_job\x18\x1d \x01(\tR\amainJob\x12\x17\n" +
	"\asub_job\x18\x1e \x01(\tR\x06subJob\x12?\n" +
	"\n" +
	"appearance\x18\x1f \x01(\v2\x1f.fantasy.v1.CharacterAppearanceR\n" +
	"appearance\x12!\n" +
	"\fimmune_until\x18  \x01(\x03R\vimmuneUntil\x12\x19\n" +
	"\bin_house\x18! \x01(\bR\ainHouse\x12\x1f\n" +
	"\vhouse_owner\x18\" \x01(\tR\n" +
	"houseOwner\"u\n" +
	"\tWorldCamp\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tR\townerName\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\x12\x12\n" +
	"\x04skin\x18\x05 \x01(\tR\x04skin\"\x80\x01\n" +
	"\x0eHouseFurniture\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12$\n" +
	"\x04item\x18\x05 \x01(\v2\x10.fantasy.v1.ItemR\x04item\"{\n" +
	"\vHousePlayer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\x12\x16\n" +
	"\x06facing\x18\x05 \x01(\x01R\x06facing\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\bR\x05owner\"^\n" +
	"\bHousePOI\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x04 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x01R\x01y\"K\n" +
	"\tSavePoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\"L\n" +
	"\n" +
	"JobChanger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\"\xaf\x03\n" +
	"\fPlayerReward\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02xp\x18\x02 \x01(\x05R\x02xp\x12\x15\n" +
	"\x06sub_xp\x18\x03 \x01(\x05R\x05subXp\x12#\n" +
	"\rlevels_gained\x18\x04 \x01(\x05R\flevelsGained\x12*\n" +
	"\x11sub_levels_gained\x18\x05 \x01(\x05R\x0fsubLevelsGained\x12\x1b\n" +
	"\tnew_level\x18\x06 \x01(\x05R\bnewLevel\x12\x15\n" +
	"\x06new_xp\x18\a \x01(\x05R\x05newXp\x12\x15\n" +
	"\x06max_xp\x18\b \x01(\x05R\x05maxXp\x12\"\n" +
	"\rsub_new_level\x18\t \x01(\x05R\vsubNewLevel\x12\x1c\n" +
	"\n" +
	"sub_new_xp\x18\n" +
	" \x01(\x05R\bsubNewXp\x12\x1c\n" +
	"\n" +
	"sub_max_xp\x18\v \x01(\x05R\bsubMaxXp\x12$\n" +
	"\x04loot\x18\f \x03(\v2\x10.fantasy.v1.ItemR\x04loot\x12\x18\n" +
	"\apassive\x18\r \x01(\bR\apassive\x12\x1f\n" +
	"\vparty_bonus\x18\x0e \x01(\bR\n" +
	"partyBonus\"\x83\x01\n" +
	"\n" +
	"FriendInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x16\n" +
	"\x06weapon\x18\x04 \x01(\tR\x06weapon\x12\x1b\n" +
	"\tin_combat\x18\x05 \x01(\bR\binCombat\"\x94\x01\n" +
	"\vPartyMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x16\n" +
	"\x06weapon\x18\x04 \x01(\tR\x06weapon\x12\x16\n" +
	"\x06leader\x18\x05 \x01(\bR\x06leader\x12\x1b\n" +
	"\tin_combat\x18\x06 \x01(\bR\binCombat\"k\n" +
	"\tPartyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x121\n" +
	"\amembers\x18\x03 \x03(\v2\x17.fantasy.v1.PartyMemberR\amembersB\"Z clara-mundi/internal/protocol/pbb\x06proto3"

var (
	file_fantasy_v1_common_proto_rawDescOnce sync.Once
	file_fantasy_v1_common_proto_rawDescData []byte
)

func file_fantasy_v1_common_proto_rawDescGZIP() []byte {
	file_fantasy_v1_common_proto_rawDescOnce.Do(func() {
		file_fantasy_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fantasy_v1_common_proto_rawDesc), len(file_fantasy_v1_common_proto_rawDesc)))
	})
	return file_fantasy_v1_common_proto_rawDescData
}

var file_fantasy_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_fantasy_v1_common_proto_goTypes = []any{
	(*CharacterAppearance)(nil), // 0: fantasy.v1.CharacterAppearance
	(*Item)(nil),                // 1: fantasy.v1.Item
	(*StatusSnapshot)(nil),      // 2: fantasy.v1.StatusSnapshot
	(*SkillInfo)(nil),           // 3: fantasy.v1.SkillInfo
	(*JobProgressInfo)(nil),     // 4: fantasy.v1.JobProgressInfo
	(*StatBlock)(nil),           // 5: fantasy.v1.StatBlock
	(*HotbarBinding)(nil),       // 6: fantasy.v1.HotbarBinding
	(*VisitedSavePoint)(nil),    // 7: fantasy.v1.VisitedSavePoint
	(*PetRecord)(nil),           // 8: fantasy.v1.PetRecord
	(*ProfileInfo)(nil),         // 9: fantasy.v1.ProfileInfo
	(*OverworldMap)(nil),        // 10: fantasy.v1.OverworldMap
	(*MapTerrainLayers)(nil),    // 11: fantasy.v1.MapTerrainLayers
	(*MapTileOverrides)(nil),    // 12: fantasy.v1.MapTileOverrides
	(*MapPortal)(nil),           // 13: fantasy.v1.MapPortal
	(*MapSnapshot)(nil),         // 14: fantasy.v1.MapSnapshot
	(*WorldEntity)(nil),         // 15: fantasy.v1.WorldEntity
	(*WorldCamp)(nil),           // 16: fantasy.v1.WorldCamp
	(*HouseFurniture)(nil),      // 17: fantasy.v1.HouseFurniture
	(*HousePlayer)(nil),         // 18: fantasy.v1.HousePlayer
	(*HousePOI)(nil),            // 19: fantasy.v1.HousePOI
	(*SavePoint)(nil),           // 20: fantasy.v1.SavePoint
	(*JobChanger)(nil),          // 21: fantasy.v1.JobChanger
	(*PlayerReward)(nil),        // 22: fantasy.v1.PlayerReward
	(*FriendInfo)(nil),          // 23: fantasy.v1.FriendInfo
	(*PartyMember)(nil),         // 24: fantasy.v1.PartyMember
	(*PartyInfo)(nil),           // 25: fantasy.v1.PartyInfo
	nil,                         // 26: fantasy.v1.Item.StatsEntry
	nil,                         // 27: fantasy.v1.ProfileInfo.EquippedEntry
	nil,                         // 28: fantasy.v1.ProfileInfo.HotbarEntry
	nil,                         // 29: fantasy.v1.ProfileInfo.KeybindsEntry
	(*structpb.Struct)(nil),     // 30: google.protobuf.Struct
}
var file_fantasy_v1_common_proto_depIdxs = []int32{
	26, // 0: fantasy.v1.Item.stats:type_name -> fantasy.v1.Item.StatsEntry
	0,  // 1: fantasy.v1.ProfileInfo.appearance:type_name -> fantasy.v1.CharacterAppearance
	4,  // 2: fantasy.v1.ProfileInfo.jobs:type_name -> fantasy.v1.JobProgressInfo
	5,  // 3: fantasy.v1.ProfileInfo.stats:type_name -> fantasy.v1.StatBlock
	1,  // 4: fantasy.v1.ProfileInfo.inventory:type_name -> fantasy.v1.Item
	27, // 5: fantasy.v1.ProfileInfo.equipped:type_name -> fantasy.v1.ProfileInfo.EquippedEntry
	28, // 6: fantasy.v1.ProfileInfo.hotbar:type_name -> fantasy.v1.ProfileInfo.HotbarEntry
	3,  // 7: fantasy.v1.ProfileInfo.skills:type_name -> fantasy.v1.SkillInfo
	7,  // 8: fantasy.v1.ProfileInfo.visited_save_points:type_name -> fantasy.v1.VisitedSavePoint
	29, // 9: fantasy.v1.ProfileInfo.keybinds:type_name -> fantasy.v1.ProfileInfo.KeybindsEntry
	1,  // 10: fantasy.v1.ProfileInfo.house_storage:type_name -> fantasy.v1.Item
	8,  // 11: fantasy.v1.ProfileInfo.pets:type_name -> fantasy.v1.PetRecord
	30, // 12: fantasy.v1.MapTileOverrides.layers:type_name -> google.protobuf.Struct
	10, // 13: fantasy.v1.MapSnapshot.overworld:type_name -> fantasy.v1.OverworldMap
	13, // 14: fantasy.v1.MapSnapshot.portals:type_name -> fantasy.v1.MapPortal
	12, // 15: fantasy.v1.MapSnapshot.tile_overrides:type_name -> fantasy.v1.MapTileOverrides
	11, // 16: fantasy.v1.MapSnapshot.terrain_layers:type_name -> fantasy.v1.MapTerrainLayers
	2,  // 17: fantasy.v1.WorldEntity.statuses:type_name -> fantasy.v1.StatusSnapshot
	0,  // 18: fantasy.v1.WorldEntity.appearance:type_name -> fantasy.v1.CharacterAppearance
	1,  // 19: fantasy.v1.HouseFurniture.item:type_name -> fantasy.v1.Item
	1,  // 20: fantasy.v1.PlayerReward.loot:type_name -> fantasy.v1.Item
	24, // 21: fantasy.v1.PartyInfo.members:type_name -> fantasy.v1.PartyMember
	6,  // 22: fantasy.v1.ProfileInfo.HotbarEntry.value:type_name -> fantasy.v1.HotbarBinding
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_fantasy_v1_common_proto_init() }
func file_fantasy_v1_common_proto_init() {
	if File_fantasy_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fantasy_v1_common_proto_rawDesc), len(file_fantasy_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fantasy_v1_common_proto_goTypes,
		DependencyIndexes: file_fantasy_v1_common_proto_depIdxs,
		MessageInfos:      file_fantasy_v1_common_proto_msgTypes,
	}.Build()
	File_fantasy_v1_common_proto = out.File
	file_fantasy_v1_common_proto_goTypes = nil
	file_fantasy_v1_common_proto_depIdxs = nil
}
