// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: fantasy/v1/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WireEnvelope is the binary frame exchanged over WebSocket BinaryMessage
// when the client negotiates codec=protobuf.
type WireEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireEnvelope) Reset() {
	*x = WireEnvelope{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireEnvelope) ProtoMessage() {}

func (x *WireEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireEnvelope.ProtoReflect.Descriptor instead.
func (*WireEnvelope) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *WireEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WireEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JoinWorldPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Race          string                 `protobuf:"bytes,2,opt,name=race,proto3" json:"race,omitempty"`
	MainJob       string                 `protobuf:"bytes,3,opt,name=main_job,json=mainJob,proto3" json:"main_job,omitempty"`
	SubJob        string                 `protobuf:"bytes,4,opt,name=sub_job,json=subJob,proto3" json:"sub_job,omitempty"`
	Job           string                 `protobuf:"bytes,5,opt,name=job,proto3" json:"job,omitempty"`
	Weapon        string                 `protobuf:"bytes,6,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Appearance    *CharacterAppearance   `protobuf:"bytes,7,opt,name=appearance,proto3" json:"appearance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinWorldPayload) Reset() {
	*x = JoinWorldPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinWorldPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldPayload) ProtoMessage() {}

func (x *JoinWorldPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldPayload.ProtoReflect.Descriptor instead.
func (*JoinWorldPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *JoinWorldPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *JoinWorldPayload) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

func (x *JoinWorldPayload) GetMainJob() string {
	if x != nil {
		return x.MainJob
	}
	return ""
}

func (x *JoinWorldPayload) GetSubJob() string {
	if x != nil {
		return x.SubJob
	}
	return ""
}

func (x *JoinWorldPayload) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *JoinWorldPayload) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *JoinWorldPayload) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

type MovePayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	X     float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	// Y-axis yaw in radians (Three.js). Optional; server derives from motion when absent.
	Facing        float64 `protobuf:"fixed64,3,opt,name=facing,proto3" json:"facing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePayload) Reset() {
	*x = MovePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePayload) ProtoMessage() {}

func (x *MovePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePayload.ProtoReflect.Descriptor instead.
func (*MovePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MovePayload) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MovePayload) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MovePayload) GetFacing() float64 {
	if x != nil {
		return x.Facing
	}
	return 0
}

type ChatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPayload) Reset() {
	*x = ChatPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPayload) ProtoMessage() {}

func (x *ChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPayload.ProtoReflect.Descriptor instead.
func (*ChatPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ChatPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EquipPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Slot          string                 `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipPayload) Reset() {
	*x = EquipPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipPayload) ProtoMessage() {}

func (x *EquipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipPayload.ProtoReflect.Descriptor instead.
func (*EquipPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *EquipPayload) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *EquipPayload) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type UnequipPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipPayload) Reset() {
	*x = UnequipPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipPayload) ProtoMessage() {}

func (x *UnequipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipPayload.ProtoReflect.Descriptor instead.
func (*UnequipPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UnequipPayload) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type SetJobsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainJob       string                 `protobuf:"bytes,1,opt,name=main_job,json=mainJob,proto3" json:"main_job,omitempty"`
	SubJob        string                 `protobuf:"bytes,2,opt,name=sub_job,json=subJob,proto3" json:"sub_job,omitempty"`
	JobChangerId  string                 `protobuf:"bytes,3,opt,name=job_changer_id,json=jobChangerId,proto3" json:"job_changer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobsPayload) Reset() {
	*x = SetJobsPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobsPayload) ProtoMessage() {}

func (x *SetJobsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobsPayload.ProtoReflect.Descriptor instead.
func (*SetJobsPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SetJobsPayload) GetMainJob() string {
	if x != nil {
		return x.MainJob
	}
	return ""
}

func (x *SetJobsPayload) GetSubJob() string {
	if x != nil {
		return x.SubJob
	}
	return ""
}

func (x *SetJobsPayload) GetJobChangerId() string {
	if x != nil {
		return x.JobChangerId
	}
	return ""
}

type SetHotbarPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHotbarPayload) Reset() {
	*x = SetHotbarPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHotbarPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHotbarPayload) ProtoMessage() {}

func (x *SetHotbarPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHotbarPayload.ProtoReflect.Descriptor instead.
func (*SetHotbarPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SetHotbarPayload) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *SetHotbarPayload) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SetHotbarPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetKeybindsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keybinds      map[string]string      `protobuf:"bytes,1,rep,name=keybinds,proto3" json:"keybinds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeybindsPayload) Reset() {
	*x = SetKeybindsPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeybindsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeybindsPayload) ProtoMessage() {}

func (x *SetKeybindsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeybindsPayload.ProtoReflect.Descriptor instead.
func (*SetKeybindsPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SetKeybindsPayload) GetKeybinds() map[string]string {
	if x != nil {
		return x.Keybinds
	}
	return nil
}

type PlayerNamePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerNamePayload) Reset() {
	*x = PlayerNamePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerNamePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerNamePayload) ProtoMessage() {}

func (x *PlayerNamePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerNamePayload.ProtoReflect.Descriptor instead.
func (*PlayerNamePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerNamePayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type PartyKickPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyKickPayload) Reset() {
	*x = PartyKickPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyKickPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyKickPayload) ProtoMessage() {}

func (x *PartyKickPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyKickPayload.ProtoReflect.Descriptor instead.
func (*PartyKickPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PartyKickPayload) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type ActionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionPayload) Reset() {
	*x = ActionPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionPayload) ProtoMessage() {}

func (x *ActionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionPayload.ProtoReflect.Descriptor instead.
func (*ActionPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ActionPayload) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ActionPayload) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ActionPayload) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type PetIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetIDPayload) Reset() {
	*x = PetIDPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetIDPayload) ProtoMessage() {}

func (x *PetIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetIDPayload.ProtoReflect.Descriptor instead.
func (*PetIDPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *PetIDPayload) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type WorldPet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	X             float64                `protobuf:"fixed64,6,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,7,opt,name=y,proto3" json:"y,omitempty"`
	Facing        float64                `protobuf:"fixed64,8,opt,name=facing,proto3" json:"facing,omitempty"` // Y-axis yaw radians
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldPet) Reset() {
	*x = WorldPet{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldPet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldPet) ProtoMessage() {}

func (x *WorldPet) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldPet.ProtoReflect.Descriptor instead.
func (*WorldPet) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *WorldPet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorldPet) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *WorldPet) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorldPet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorldPet) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *WorldPet) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WorldPet) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WorldPet) GetFacing() float64 {
	if x != nil {
		return x.Facing
	}
	return 0
}

type PetStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*WorldPet            `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetStatePayload) Reset() {
	*x = PetStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetStatePayload) ProtoMessage() {}

func (x *PetStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetStatePayload.ProtoReflect.Descriptor instead.
func (*PetStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *PetStatePayload) GetPets() []*WorldPet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type SetTargetPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTargetPayload) Reset() {
	*x = SetTargetPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetPayload) ProtoMessage() {}

func (x *SetTargetPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetPayload.ProtoReflect.Descriptor instead.
func (*SetTargetPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SetTargetPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type SetSavePointPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavePointId   string                 `protobuf:"bytes,1,opt,name=save_point_id,json=savePointId,proto3" json:"save_point_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSavePointPayload) Reset() {
	*x = SetSavePointPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSavePointPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSavePointPayload) ProtoMessage() {}

func (x *SetSavePointPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSavePointPayload.ProtoReflect.Descriptor instead.
func (*SetSavePointPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *SetSavePointPayload) GetSavePointId() string {
	if x != nil {
		return x.SavePointId
	}
	return ""
}

type UseWorldSkillPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	SavePointId   string                 `protobuf:"bytes,2,opt,name=save_point_id,json=savePointId,proto3" json:"save_point_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseWorldSkillPayload) Reset() {
	*x = UseWorldSkillPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseWorldSkillPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseWorldSkillPayload) ProtoMessage() {}

func (x *UseWorldSkillPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseWorldSkillPayload.ProtoReflect.Descriptor instead.
func (*UseWorldSkillPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *UseWorldSkillPayload) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *UseWorldSkillPayload) GetSavePointId() string {
	if x != nil {
		return x.SavePointId
	}
	return ""
}

type EnterHousePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterHousePayload) Reset() {
	*x = EnterHousePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterHousePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterHousePayload) ProtoMessage() {}

func (x *EnterHousePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterHousePayload.ProtoReflect.Descriptor instead.
func (*EnterHousePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *EnterHousePayload) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type HouseInteractPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseInteractPayload) Reset() {
	*x = HouseInteractPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseInteractPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseInteractPayload) ProtoMessage() {}

func (x *HouseInteractPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseInteractPayload.ProtoReflect.Descriptor instead.
func (*HouseInteractPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *HouseInteractPayload) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type HouseStorageMovePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Qty           int32                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseStorageMovePayload) Reset() {
	*x = HouseStorageMovePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseStorageMovePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseStorageMovePayload) ProtoMessage() {}

func (x *HouseStorageMovePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseStorageMovePayload.ProtoReflect.Descriptor instead.
func (*HouseStorageMovePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *HouseStorageMovePayload) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *HouseStorageMovePayload) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type HousePlaceFurniturePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HousePlaceFurniturePayload) Reset() {
	*x = HousePlaceFurniturePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HousePlaceFurniturePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HousePlaceFurniturePayload) ProtoMessage() {}

func (x *HousePlaceFurniturePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HousePlaceFurniturePayload.ProtoReflect.Descriptor instead.
func (*HousePlaceFurniturePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{21}
}

func (x *HousePlaceFurniturePayload) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *HousePlaceFurniturePayload) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *HousePlaceFurniturePayload) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

type HousePickFurniturePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FurnitureId   string                 `protobuf:"bytes,1,opt,name=furniture_id,json=furnitureId,proto3" json:"furniture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HousePickFurniturePayload) Reset() {
	*x = HousePickFurniturePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HousePickFurniturePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HousePickFurniturePayload) ProtoMessage() {}

func (x *HousePickFurniturePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HousePickFurniturePayload.ProtoReflect.Descriptor instead.
func (*HousePickFurniturePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *HousePickFurniturePayload) GetFurnitureId() string {
	if x != nil {
		return x.FurnitureId
	}
	return ""
}

type SetCampSkinPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skin          string                 `protobuf:"bytes,1,opt,name=skin,proto3" json:"skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCampSkinPayload) Reset() {
	*x = SetCampSkinPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCampSkinPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCampSkinPayload) ProtoMessage() {}

func (x *SetCampSkinPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCampSkinPayload.ProtoReflect.Descriptor instead.
func (*SetCampSkinPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{23}
}

func (x *SetCampSkinPayload) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

type CampStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Camps         []*WorldCamp           `protobuf:"bytes,1,rep,name=camps,proto3" json:"camps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampStatePayload) Reset() {
	*x = CampStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampStatePayload) ProtoMessage() {}

func (x *CampStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampStatePayload.ProtoReflect.Descriptor instead.
func (*CampStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{24}
}

func (x *CampStatePayload) GetCamps() []*WorldCamp {
	if x != nil {
		return x.Camps
	}
	return nil
}

type HouseStatePayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerName       string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Skin            string                 `protobuf:"bytes,2,opt,name=skin,proto3" json:"skin,omitempty"`
	MapCols         int32                  `protobuf:"varint,3,opt,name=map_cols,json=mapCols,proto3" json:"map_cols,omitempty"`
	MapRows         int32                  `protobuf:"varint,4,opt,name=map_rows,json=mapRows,proto3" json:"map_rows,omitempty"`
	WalkCols        int32                  `protobuf:"varint,5,opt,name=walk_cols,json=walkCols,proto3" json:"walk_cols,omitempty"`
	WalkRows        int32                  `protobuf:"varint,6,opt,name=walk_rows,json=walkRows,proto3" json:"walk_rows,omitempty"`
	WalkOriginCol   int32                  `protobuf:"varint,7,opt,name=walk_origin_col,json=walkOriginCol,proto3" json:"walk_origin_col,omitempty"`
	WalkOriginRow   int32                  `protobuf:"varint,8,opt,name=walk_origin_row,json=walkOriginRow,proto3" json:"walk_origin_row,omitempty"`
	TileSize        int32                  `protobuf:"varint,9,opt,name=tile_size,json=tileSize,proto3" json:"tile_size,omitempty"`
	Players         []*HousePlayer         `protobuf:"bytes,10,rep,name=players,proto3" json:"players,omitempty"`
	Furniture       []*HouseFurniture      `protobuf:"bytes,11,rep,name=furniture,proto3" json:"furniture,omitempty"`
	Pois            []*HousePOI            `protobuf:"bytes,12,rep,name=pois,proto3" json:"pois,omitempty"`
	Storage         []*Item                `protobuf:"bytes,13,rep,name=storage,proto3" json:"storage,omitempty"`
	StorageCapacity int32                  `protobuf:"varint,14,opt,name=storage_capacity,json=storageCapacity,proto3" json:"storage_capacity,omitempty"`
	IsOwner         bool                   `protobuf:"varint,15,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HouseStatePayload) Reset() {
	*x = HouseStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseStatePayload) ProtoMessage() {}

func (x *HouseStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseStatePayload.ProtoReflect.Descriptor instead.
func (*HouseStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{25}
}

func (x *HouseStatePayload) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *HouseStatePayload) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

func (x *HouseStatePayload) GetMapCols() int32 {
	if x != nil {
		return x.MapCols
	}
	return 0
}

func (x *HouseStatePayload) GetMapRows() int32 {
	if x != nil {
		return x.MapRows
	}
	return 0
}

func (x *HouseStatePayload) GetWalkCols() int32 {
	if x != nil {
		return x.WalkCols
	}
	return 0
}

func (x *HouseStatePayload) GetWalkRows() int32 {
	if x != nil {
		return x.WalkRows
	}
	return 0
}

func (x *HouseStatePayload) GetWalkOriginCol() int32 {
	if x != nil {
		return x.WalkOriginCol
	}
	return 0
}

func (x *HouseStatePayload) GetWalkOriginRow() int32 {
	if x != nil {
		return x.WalkOriginRow
	}
	return 0
}

func (x *HouseStatePayload) GetTileSize() int32 {
	if x != nil {
		return x.TileSize
	}
	return 0
}

func (x *HouseStatePayload) GetPlayers() []*HousePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *HouseStatePayload) GetFurniture() []*HouseFurniture {
	if x != nil {
		return x.Furniture
	}
	return nil
}

func (x *HouseStatePayload) GetPois() []*HousePOI {
	if x != nil {
		return x.Pois
	}
	return nil
}

func (x *HouseStatePayload) GetStorage() []*Item {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *HouseStatePayload) GetStorageCapacity() int32 {
	if x != nil {
		return x.StorageCapacity
	}
	return 0
}

func (x *HouseStatePayload) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type HouseReturnPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseReturnPayload) Reset() {
	*x = HouseReturnPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseReturnPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseReturnPayload) ProtoMessage() {}

func (x *HouseReturnPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseReturnPayload.ProtoReflect.Descriptor instead.
func (*HouseReturnPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{26}
}

func (x *HouseReturnPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type WelcomePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Profile       *ProfileInfo           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Map           *MapSnapshot           `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomePayload) Reset() {
	*x = WelcomePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePayload) ProtoMessage() {}

func (x *WelcomePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePayload.ProtoReflect.Descriptor instead.
func (*WelcomePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{27}
}

func (x *WelcomePayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *WelcomePayload) GetProfile() *ProfileInfo {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *WelcomePayload) GetMap() *MapSnapshot {
	if x != nil {
		return x.Map
	}
	return nil
}

type MapConfigPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           *MapSnapshot           `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapConfigPayload) Reset() {
	*x = MapConfigPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapConfigPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapConfigPayload) ProtoMessage() {}

func (x *MapConfigPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapConfigPayload.ProtoReflect.Descriptor instead.
func (*MapConfigPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{28}
}

func (x *MapConfigPayload) GetMap() *MapSnapshot {
	if x != nil {
		return x.Map
	}
	return nil
}

type WorldStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*WorldPlayer         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Npcs          []*WorldNPC            `protobuf:"bytes,2,rep,name=npcs,proto3" json:"npcs,omitempty"`
	SavePoints    []*SavePoint           `protobuf:"bytes,4,rep,name=save_points,json=savePoints,proto3" json:"save_points,omitempty"`
	JobChangers   []*JobChanger          `protobuf:"bytes,5,rep,name=job_changers,json=jobChangers,proto3" json:"job_changers,omitempty"`
	Map           *OverworldMap          `protobuf:"bytes,6,opt,name=map,proto3" json:"map,omitempty"`
	Camps         []*WorldCamp           `protobuf:"bytes,7,rep,name=camps,proto3" json:"camps,omitempty"`
	Pets          []*WorldPet            `protobuf:"bytes,8,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldStatePayload) Reset() {
	*x = WorldStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldStatePayload) ProtoMessage() {}

func (x *WorldStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldStatePayload.ProtoReflect.Descriptor instead.
func (*WorldStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{29}
}

func (x *WorldStatePayload) GetPlayers() []*WorldPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldStatePayload) GetNpcs() []*WorldNPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *WorldStatePayload) GetSavePoints() []*SavePoint {
	if x != nil {
		return x.SavePoints
	}
	return nil
}

func (x *WorldStatePayload) GetJobChangers() []*JobChanger {
	if x != nil {
		return x.JobChangers
	}
	return nil
}

func (x *WorldStatePayload) GetMap() *OverworldMap {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *WorldStatePayload) GetCamps() []*WorldCamp {
	if x != nil {
		return x.Camps
	}
	return nil
}

func (x *WorldStatePayload) GetPets() []*WorldPet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type PlayerLeftPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeftPayload) Reset() {
	*x = PlayerLeftPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftPayload) ProtoMessage() {}

func (x *PlayerLeftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftPayload.ProtoReflect.Descriptor instead.
func (*PlayerLeftPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{30}
}

func (x *PlayerLeftPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlayerMovedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Facing        float64                `protobuf:"fixed64,4,opt,name=facing,proto3" json:"facing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMovedPayload) Reset() {
	*x = PlayerMovedPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMovedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMovedPayload) ProtoMessage() {}

func (x *PlayerMovedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMovedPayload.ProtoReflect.Descriptor instead.
func (*PlayerMovedPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{31}
}

func (x *PlayerMovedPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerMovedPayload) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMovedPayload) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerMovedPayload) GetFacing() float64 {
	if x != nil {
		return x.Facing
	}
	return 0
}

type ChatMessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessagePayload) Reset() {
	*x = ChatMessagePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessagePayload) ProtoMessage() {}

func (x *ChatMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessagePayload.ProtoReflect.Descriptor instead.
func (*ChatMessagePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{32}
}

func (x *ChatMessagePayload) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *ChatMessagePayload) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *ChatMessagePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessagePayload) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type NPCStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Npcs          []*WorldNPC            `protobuf:"bytes,1,rep,name=npcs,proto3" json:"npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NPCStatePayload) Reset() {
	*x = NPCStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPCStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPCStatePayload) ProtoMessage() {}

func (x *NPCStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPCStatePayload.ProtoReflect.Descriptor instead.
func (*NPCStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{33}
}

func (x *NPCStatePayload) GetNpcs() []*WorldNPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

type PartyInvitePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	PartyId       string                 `protobuf:"bytes,3,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInvitePayload) Reset() {
	*x = PartyInvitePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInvitePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInvitePayload) ProtoMessage() {}

func (x *PartyInvitePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInvitePayload.ProtoReflect.Descriptor instead.
func (*PartyInvitePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{34}
}

func (x *PartyInvitePayload) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *PartyInvitePayload) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *PartyInvitePayload) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type FriendRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestPayload) Reset() {
	*x = FriendRequestPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestPayload) ProtoMessage() {}

func (x *FriendRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestPayload.ProtoReflect.Descriptor instead.
func (*FriendRequestPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{35}
}

func (x *FriendRequestPayload) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *FriendRequestPayload) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

type RewardNoticePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xp            int32                  `protobuf:"varint,1,opt,name=xp,proto3" json:"xp,omitempty"`
	Passive       bool                   `protobuf:"varint,2,opt,name=passive,proto3" json:"passive,omitempty"`
	Victory       bool                   `protobuf:"varint,3,opt,name=victory,proto3" json:"victory,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardNoticePayload) Reset() {
	*x = RewardNoticePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardNoticePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardNoticePayload) ProtoMessage() {}

func (x *RewardNoticePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardNoticePayload.ProtoReflect.Descriptor instead.
func (*RewardNoticePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{36}
}

func (x *RewardNoticePayload) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *RewardNoticePayload) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *RewardNoticePayload) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *RewardNoticePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SocialStatePayload struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Friends                []*FriendInfo           `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Party                  *PartyInfo              `protobuf:"bytes,2,opt,name=party,proto3" json:"party,omitempty"`
	PendingInvite          *PartyInvitePayload     `protobuf:"bytes,3,opt,name=pending_invite,json=pendingInvite,proto3" json:"pending_invite,omitempty"`
	PendingFriendRequests  []*FriendRequestPayload `protobuf:"bytes,4,rep,name=pending_friend_requests,json=pendingFriendRequests,proto3" json:"pending_friend_requests,omitempty"`
	OutgoingFriendRequests []string                `protobuf:"bytes,5,rep,name=outgoing_friend_requests,json=outgoingFriendRequests,proto3" json:"outgoing_friend_requests,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SocialStatePayload) Reset() {
	*x = SocialStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialStatePayload) ProtoMessage() {}

func (x *SocialStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialStatePayload.ProtoReflect.Descriptor instead.
func (*SocialStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{37}
}

func (x *SocialStatePayload) GetFriends() []*FriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *SocialStatePayload) GetParty() *PartyInfo {
	if x != nil {
		return x.Party
	}
	return nil
}

func (x *SocialStatePayload) GetPendingInvite() *PartyInvitePayload {
	if x != nil {
		return x.PendingInvite
	}
	return nil
}

func (x *SocialStatePayload) GetPendingFriendRequests() []*FriendRequestPayload {
	if x != nil {
		return x.PendingFriendRequests
	}
	return nil
}

func (x *SocialStatePayload) GetOutgoingFriendRequests() []string {
	if x != nil {
		return x.OutgoingFriendRequests
	}
	return nil
}

type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{38}
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CombatTickPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*CombatEntity        `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatTickPayload) Reset() {
	*x = CombatTickPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatTickPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatTickPayload) ProtoMessage() {}

func (x *CombatTickPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatTickPayload.ProtoReflect.Descriptor instead.
func (*CombatTickPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{39}
}

func (x *CombatTickPayload) GetEntities() []*CombatEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type CombatEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    string                 `protobuf:"bytes,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	Heal          int32                  `protobuf:"varint,4,opt,name=heal,proto3" json:"heal,omitempty"`
	MpRestored    int32                  `protobuf:"varint,5,opt,name=mp_restored,json=mpRestored,proto3" json:"mp_restored,omitempty"`
	Hit           bool                   `protobuf:"varint,6,opt,name=hit,proto3" json:"hit,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	ActionId      string                 `protobuf:"bytes,8,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionName    string                 `protobuf:"bytes,9,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Success       bool                   `protobuf:"varint,10,opt,name=success,proto3" json:"success,omitempty"`
	CastStarted   bool                   `protobuf:"varint,11,opt,name=cast_started,json=castStarted,proto3" json:"cast_started,omitempty"`
	CastCancelled bool                   `protobuf:"varint,12,opt,name=cast_cancelled,json=castCancelled,proto3" json:"cast_cancelled,omitempty"`
	Entities      []*CombatEntity        `protobuf:"bytes,13,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatEventPayload) Reset() {
	*x = CombatEventPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatEventPayload) ProtoMessage() {}

func (x *CombatEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatEventPayload.ProtoReflect.Descriptor instead.
func (*CombatEventPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{40}
}

func (x *CombatEventPayload) GetAttackerId() string {
	if x != nil {
		return x.AttackerId
	}
	return ""
}

func (x *CombatEventPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CombatEventPayload) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CombatEventPayload) GetHeal() int32 {
	if x != nil {
		return x.Heal
	}
	return 0
}

func (x *CombatEventPayload) GetMpRestored() int32 {
	if x != nil {
		return x.MpRestored
	}
	return 0
}

func (x *CombatEventPayload) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *CombatEventPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CombatEventPayload) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *CombatEventPayload) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *CombatEventPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CombatEventPayload) GetCastStarted() bool {
	if x != nil {
		return x.CastStarted
	}
	return false
}

func (x *CombatEventPayload) GetCastCancelled() bool {
	if x != nil {
		return x.CastCancelled
	}
	return false
}

func (x *CombatEventPayload) GetEntities() []*CombatEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// EmptyPayload covers dodge, party_accept, leave_house, etc.
type EmptyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyPayload) Reset() {
	*x = EmptyPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyPayload) ProtoMessage() {}

func (x *EmptyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyPayload.ProtoReflect.Descriptor instead.
func (*EmptyPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{41}
}

var File_fantasy_v1_messages_proto protoreflect.FileDescriptor

const file_fantasy_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x19fantasy/v1/messages.proto\x12\n" +
	"fantasy.v1\x1a\x17fantasy/v1/common.proto\"<\n" +
	"\fWireEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xe6\x01\n" +
	"\x10JoinWorldPayload\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x12\n" +
	"\x04race\x18\x02 \x01(\tR\x04race\x12\x19\n" +
	"\bmain_job\x18\x03 \x01(\tR\amainJob\x12\x17\n" +
	"\asub_job\x18\x04 \x01(\tR\x06subJob\x12\x10\n" +
	"\x03job\x18\x05 \x01(\tR\x03job\x12\x16\n" +
	"\x06weapon\x18\x06 \x01(\tR\x06weapon\x12?\n" +
	"\n" +
	"appearance\x18\a \x01(\v2\x1f.fantasy.v1.CharacterAppearanceR\n" +
	"appearance\"A\n" +
	"\vMovePayload\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x16\n" +
	"\x06facing\x18\x03 \x01(\x01R\x06facing\"'\n" +
	"\vChatPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\fEquipPayload\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\tR\x04slot\"$\n" +
	"\x0eUnequipPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"j\n" +
	"\x0eSetJobsPayload\x12\x19\n" +
	"\bmain_job\x18\x01 \x01(\tR\amainJob\x12\x17\n" +
	"\asub_job\x18\x02 \x01(\tR\x06subJob\x12$\n" +
	"\x0ejob_changer_id\x18\x03 \x01(\tR\fjobChangerId\"J\n" +
	"\x10SetHotbarPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\x9b\x01\n" +
	"\x12SetKeybindsPayload\x12H\n" +
	"\bkeybinds\x18\x01 \x03(\v2,.fantasy.v1.SetKeybindsPayload.KeybindsEntryR\bkeybinds\x1a;\n" +
	"\rKeybindsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11PlayerNamePayload\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"/\n" +
	"\x10PartyKickPayload\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"}\n" +
	"\rActionPayload\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\"%\n" +
	"\fPetIDPayload\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\"\xa7\x01\n" +
	"\bWorldPet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\f\n" +
	"\x01x\x18\x06 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\a \x01(\x01R\x01y\x12\x16\n" +
	"\x06facing\x18\b \x01(\x01R\x06facing\";\n" +
	"\x0fPetStatePayload\x12(\n" +
	"\x04pets\x18\x01 \x03(\v2\x14.fantasy.v1.WorldPetR\x04pets\"/\n" +
	"\x10SetTargetPayload\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"9\n" +
	"\x13SetSavePointPayload\x12\"\n" +
	"\rsave_point_id\x18\x01 \x01(\tR\vsavePointId\"U\n" +
	"\x14UseWorldSkillPayload\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\"\n" +
	"\rsave_point_id\x18\x02 \x01(\tR\vsavePointId\"2\n" +
	"\x11EnterHousePayload\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tR\townerName\".\n" +
	"\x14HouseInteractPayload\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"D\n" +
	"\x17HouseStorageMovePayload\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x05R\x03qty\"Y\n" +
	"\x1aHousePlaceFurniturePayload\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\">\n" +
	"\x19HousePickFurniturePayload\x12!\n" +
	"\ffurniture_id\x18\x01 \x01(\tR\vfurnitureId\"(\n" +
	"\x12SetCampSkinPayload\x12\x12\n" +
	"\x04skin\x18\x01 \x01(\tR\x04skin\"?\n" +
	"\x10CampStatePayload\x12+\n" +
	"\x05camps\x18\x01 \x03(\v2\x15.fantasy.v1.WorldCampR\x05camps\"\xac\x04\n" +
	"\x11HouseStatePayload\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tR\townerName\x12\x12\n" +
	"\x04skin\x18\x02 \x01(\tR\x04skin\x12\x19\n" +
	"\bmap_cols\x18\x03 \x01(\x05R\amapCols\x12\x19\n" +
	"\bmap_rows\x18\x04 \x01(\x05R\amapRows\x12\x1b\n" +
	"\twalk_cols\x18\x05 \x01(\x05R\bwalkCols\x12\x1b\n" +
	"\twalk_rows\x18\x06 \x01(\x05R\bwalkRows\x12&\n" +
	"\x0fwalk_origin_col\x18\a \x01(\x05R\rwalkOriginCol\x12&\n" +
	"\x0fwalk_origin_row\x18\b \x01(\x05R\rwalkOriginRow\x12\x1b\n" +
	"\ttile_size\x18\t \x01(\x05R\btileSize\x121\n" +
	"\aplayers\x18\n" +
	" \x03(\v2\x17.fantasy.v1.HousePlayerR\aplayers\x128\n" +
	"\tfurniture\x18\v \x03(\v2\x1a.fantasy.v1.HouseFurnitureR\tfurniture\x12(\n" +
	"\x04pois\x18\f \x03(\v2\x14.fantasy.v1.HousePOIR\x04pois\x12*\n" +
	"\astorage\x18\r \x03(\v2\x10.fantasy.v1.ItemR\astorage\x12)\n" +
	"\x10storage_capacity\x18\x0e \x01(\x05R\x0fstorageCapacity\x12\x19\n" +
	"\bis_owner\x18\x0f \x01(\bR\aisOwner\",\n" +
	"\x12HouseReturnPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x8b\x01\n" +
	"\x0eWelcomePayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x121\n" +
	"\aprofile\x18\x02 \x01(\v2\x17.fantasy.v1.ProfileInfoR\aprofile\x12)\n" +
	"\x03map\x18\x03 \x01(\v2\x17.fantasy.v1.MapSnapshotR\x03map\"=\n" +
	"\x10MapConfigPayload\x12)\n" +
	"\x03map\x18\x01 \x01(\v2\x17.fantasy.v1.MapSnapshotR\x03map\"\xe6\x02\n" +
	"\x11WorldStatePayload\x121\n" +
	"\aplayers\x18\x01 \x03(\v2\x17.fantasy.v1.WorldPlayerR\aplayers\x12(\n" +
	"\x04npcs\x18\x02 \x03(\v2\x14.fantasy.v1.WorldNPCR\x04npcs\x126\n" +
	"\vsave_points\x18\x04 \x03(\v2\x15.fantasy.v1.SavePointR\n" +
	"savePoints\x129\n" +
	"\fjob_changers\x18\x05 \x03(\v2\x16.fantasy.v1.JobChangerR\vjobChangers\x12*\n" +
	"\x03map\x18\x06 \x01(\v2\x18.fantasy.v1.OverworldMapR\x03map\x12+\n" +
	"\x05camps\x18\a \x03(\v2\x15.fantasy.v1.WorldCampR\x05camps\x12(\n" +
	"\x04pets\x18\b \x03(\v2\x14.fantasy.v1.WorldPetR\x04pets\"#\n" +
	"\x11PlayerLeftPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x12PlayerMovedPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x16\n" +
	"\x06facing\x18\x04 \x01(\x01R\x06facing\"~\n" +
	"\x12ChatMessagePayload\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\";\n" +
	"\x0fNPCStatePayload\x12(\n" +
	"\x04npcs\x18\x01 \x03(\v2\x14.fantasy.v1.WorldNPCR\x04npcs\"e\n" +
	"\x12PartyInvitePayload\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\x12\x19\n" +
	"\bparty_id\x18\x03 \x01(\tR\apartyId\"L\n" +
	"\x14FriendRequestPayload\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\"s\n" +
	"\x13RewardNoticePayload\x12\x0e\n" +
	"\x02xp\x18\x01 \x01(\x05R\x02xp\x12\x18\n" +
	"\apassive\x18\x02 \x01(\bR\apassive\x12\x18\n" +
	"\avictory\x18\x03 \x01(\bR\avictory\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xce\x02\n" +
	"\x12SocialStatePayload\x120\n" +
	"\afriends\x18\x01 \x03(\v2\x16.fantasy.v1.FriendInfoR\afriends\x12+\n" +
	"\x05party\x18\x02 \x01(\v2\x15.fantasy.v1.PartyInfoR\x05party\x12E\n" +
	"\x0epending_invite\x18\x03 \x01(\v2\x1e.fantasy.v1.PartyInvitePayloadR\rpendingInvite\x12X\n" +
	"\x17pending_friend_requests\x18\x04 \x03(\v2 .fantasy.v1.FriendRequestPayloadR\x15pendingFriendRequests\x128\n" +
	"\x18outgoing_friend_requests\x18\x05 \x03(\tR\x16outgoingFriendRequests\"(\n" +
	"\fErrorPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"I\n" +
	"\x11CombatTickPayload\x124\n" +
	"\bentities\x18\x01 \x03(\v2\x18.fantasy.v1.CombatEntityR\bentities\"\xa3\x03\n" +
	"\x12CombatEventPayload\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\tR\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12\x12\n" +
	"\x04heal\x18\x04 \x01(\x05R\x04heal\x12\x1f\n" +
	"\vmp_restored\x18\x05 \x01(\x05R\n" +
	"mpRestored\x12\x10\n" +
	"\x03hit\x18\x06 \x01(\bR\x03hit\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1b\n" +
	"\taction_id\x18\b \x01(\tR\bactionId\x12\x1f\n" +
	"\vaction_name\x18\t \x01(\tR\n" +
	"actionName\x12\x18\n" +
	"\asuccess\x18\n" +
	" \x01(\bR\asuccess\x12!\n" +
	"\fcast_started\x18\v \x01(\bR\vcastStarted\x12%\n" +
	"\x0ecast_cancelled\x18\f \x01(\bR\rcastCancelled\x124\n" +
	"\bentities\x18\r \x03(\v2\x18.fantasy.v1.CombatEntityR\bentities\"\x0e\n" +
	"\fEmptyPayloadB\"Z clara-mundi/internal/protocol/pbb\x06proto3"

var (
	file_fantasy_v1_messages_proto_rawDescOnce sync.Once
	file_fantasy_v1_messages_proto_rawDescData []byte
)

func file_fantasy_v1_messages_proto_rawDescGZIP() []byte {
	file_fantasy_v1_messages_proto_rawDescOnce.Do(func() {
		file_fantasy_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fantasy_v1_messages_proto_rawDesc), len(file_fantasy_v1_messages_proto_rawDesc)))
	})
	return file_fantasy_v1_messages_proto_rawDescData
}

var file_fantasy_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_fantasy_v1_messages_proto_goTypes = []any{
	(*WireEnvelope)(nil),               // 0: fantasy.v1.WireEnvelope
	(*JoinWorldPayload)(nil),           // 1: fantasy.v1.JoinWorldPayload
	(*MovePayload)(nil),                // 2: fantasy.v1.MovePayload
	(*ChatPayload)(nil),                // 3: fantasy.v1.ChatPayload
	(*EquipPayload)(nil),               // 4: fantasy.v1.EquipPayload
	(*UnequipPayload)(nil),             // 5: fantasy.v1.UnequipPayload
	(*SetJobsPayload)(nil),             // 6: fantasy.v1.SetJobsPayload
	(*SetHotbarPayload)(nil),           // 7: fantasy.v1.SetHotbarPayload
	(*SetKeybindsPayload)(nil),         // 8: fantasy.v1.SetKeybindsPayload
	(*PlayerNamePayload)(nil),          // 9: fantasy.v1.PlayerNamePayload
	(*PartyKickPayload)(nil),           // 10: fantasy.v1.PartyKickPayload
	(*ActionPayload)(nil),              // 11: fantasy.v1.ActionPayload
	(*PetIDPayload)(nil),               // 12: fantasy.v1.PetIDPayload
	(*WorldPet)(nil),                   // 13: fantasy.v1.WorldPet
	(*PetStatePayload)(nil),            // 14: fantasy.v1.PetStatePayload
	(*SetTargetPayload)(nil),           // 15: fantasy.v1.SetTargetPayload
	(*SetSavePointPayload)(nil),        // 16: fantasy.v1.SetSavePointPayload
	(*UseWorldSkillPayload)(nil),       // 17: fantasy.v1.UseWorldSkillPayload
	(*EnterHousePayload)(nil),          // 18: fantasy.v1.EnterHousePayload
	(*HouseInteractPayload)(nil),       // 19: fantasy.v1.HouseInteractPayload
	(*HouseStorageMovePayload)(nil),    // 20: fantasy.v1.HouseStorageMovePayload
	(*HousePlaceFurniturePayload)(nil), // 21: fantasy.v1.HousePlaceFurniturePayload
	(*HousePickFurniturePayload)(nil),  // 22: fantasy.v1.HousePickFurniturePayload
	(*SetCampSkinPayload)(nil),         // 23: fantasy.v1.SetCampSkinPayload
	(*CampStatePayload)(nil),           // 24: fantasy.v1.CampStatePayload
	(*HouseStatePayload)(nil),          // 25: fantasy.v1.HouseStatePayload
	(*HouseReturnPayload)(nil),         // 26: fantasy.v1.HouseReturnPayload
	(*WelcomePayload)(nil),             // 27: fantasy.v1.WelcomePayload
	(*MapConfigPayload)(nil),           // 28: fantasy.v1.MapConfigPayload
	(*WorldStatePayload)(nil),          // 29: fantasy.v1.WorldStatePayload
	(*PlayerLeftPayload)(nil),          // 30: fantasy.v1.PlayerLeftPayload
	(*PlayerMovedPayload)(nil),         // 31: fantasy.v1.PlayerMovedPayload
	(*ChatMessagePayload)(nil),         // 32: fantasy.v1.ChatMessagePayload
	(*NPCStatePayload)(nil),            // 33: fantasy.v1.NPCStatePayload
	(*PartyInvitePayload)(nil),         // 34: fantasy.v1.PartyInvitePayload
	(*FriendRequestPayload)(nil),       // 35: fantasy.v1.FriendRequestPayload
	(*RewardNoticePayload)(nil),        // 36: fantasy.v1.RewardNoticePayload
	(*SocialStatePayload)(nil),         // 37: fantasy.v1.SocialStatePayload
	(*ErrorPayload)(nil),               // 38: fantasy.v1.ErrorPayload
	(*CombatTickPayload)(nil),          // 39: fantasy.v1.CombatTickPayload
	(*CombatEventPayload)(nil),         // 40: fantasy.v1.CombatEventPayload
	(*EmptyPayload)(nil),               // 41: fantasy.v1.EmptyPayload
	nil,                                // 42: fantasy.v1.SetKeybindsPayload.KeybindsEntry
	(*CharacterAppearance)(nil),        // 43: fantasy.v1.CharacterAppearance
	(*WorldCamp)(nil),                  // 44: fantasy.v1.WorldCamp
	(*HousePlayer)(nil),                // 45: fantasy.v1.HousePlayer
	(*HouseFurniture)(nil),             // 46: fantasy.v1.HouseFurniture
	(*HousePOI)(nil),                   // 47: fantasy.v1.HousePOI
	(*Item)(nil),                       // 48: fantasy.v1.Item
	(*ProfileInfo)(nil),                // 49: fantasy.v1.ProfileInfo
	(*MapSnapshot)(nil),                // 50: fantasy.v1.MapSnapshot
	(*WorldPlayer)(nil),                // 51: fantasy.v1.WorldPlayer
	(*WorldNPC)(nil),                   // 52: fantasy.v1.WorldNPC
	(*SavePoint)(nil),                  // 53: fantasy.v1.SavePoint
	(*JobChanger)(nil),                 // 54: fantasy.v1.JobChanger
	(*OverworldMap)(nil),               // 55: fantasy.v1.OverworldMap
	(*FriendInfo)(nil),                 // 56: fantasy.v1.FriendInfo
	(*PartyInfo)(nil),                  // 57: fantasy.v1.PartyInfo
	(*CombatEntity)(nil),               // 58: fantasy.v1.CombatEntity
}
var file_fantasy_v1_messages_proto_depIdxs = []int32{
	43, // 0: fantasy.v1.JoinWorldPayload.appearance:type_name -> fantasy.v1.CharacterAppearance
	42, // 1: fantasy.v1.SetKeybindsPayload.keybinds:type_name -> fantasy.v1.SetKeybindsPayload.KeybindsEntry
	13, // 2: fantasy.v1.PetStatePayload.pets:type_name -> fantasy.v1.WorldPet
	44, // 3: fantasy.v1.CampStatePayload.camps:type_name -> fantasy.v1.WorldCamp
	45, // 4: fantasy.v1.HouseStatePayload.players:type_name -> fantasy.v1.HousePlayer
	46, // 5: fantasy.v1.HouseStatePayload.furniture:type_name -> fantasy.v1.HouseFurniture
	47, // 6: fantasy.v1.HouseStatePayload.pois:type_name -> fantasy.v1.HousePOI
	48, // 7: fantasy.v1.HouseStatePayload.storage:type_name -> fantasy.v1.Item
	49, // 8: fantasy.v1.WelcomePayload.profile:type_name -> fantasy.v1.ProfileInfo
	50, // 9: fantasy.v1.WelcomePayload.map:type_name -> fantasy.v1.MapSnapshot
	50, // 10: fantasy.v1.MapConfigPayload.map:type_name -> fantasy.v1.MapSnapshot
	51, // 11: fantasy.v1.WorldStatePayload.players:type_name -> fantasy.v1.WorldPlayer
	52, // 12: fantasy.v1.WorldStatePayload.npcs:type_name -> fantasy.v1.WorldNPC
	53, // 13: fantasy.v1.WorldStatePayload.save_points:type_name -> fantasy.v1.SavePoint
	54, // 14: fantasy.v1.WorldStatePayload.job_changers:type_name -> fantasy.v1.JobChanger
	55, // 15: fantasy.v1.WorldStatePayload.map:type_name -> fantasy.v1.OverworldMap
	44, // 16: fantasy.v1.WorldStatePayload.camps:type_name -> fantasy.v1.WorldCamp
	13, // 17: fantasy.v1.WorldStatePayload.pets:type_name -> fantasy.v1.WorldPet
	52, // 18: fantasy.v1.NPCStatePayload.npcs:type_name -> fantasy.v1.WorldNPC
	56, // 19: fantasy.v1.SocialStatePayload.friends:type_name -> fantasy.v1.FriendInfo
	57, // 20: fantasy.v1.SocialStatePayload.party:type_name -> fantasy.v1.PartyInfo
	34, // 21: fantasy.v1.SocialStatePayload.pending_invite:type_name -> fantasy.v1.PartyInvitePayload
	35, // 22: fantasy.v1.SocialStatePayload.pending_friend_requests:type_name -> fantasy.v1.FriendRequestPayload
	58, // 23: fantasy.v1.CombatTickPayload.entities:type_name -> fantasy.v1.CombatEntity
	58, // 24: fantasy.v1.CombatEventPayload.entities:type_name -> fantasy.v1.CombatEntity
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_fantasy_v1_messages_proto_init() }
func file_fantasy_v1_messages_proto_init() {
	if File_fantasy_v1_messages_proto != nil {
		return
	}
	file_fantasy_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fantasy_v1_messages_proto_rawDesc), len(file_fantasy_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fantasy_v1_messages_proto_goTypes,
		DependencyIndexes: file_fantasy_v1_messages_proto_depIdxs,
		MessageInfos:      file_fantasy_v1_messages_proto_msgTypes,
	}.Build()
	File_fantasy_v1_messages_proto = out.File
	file_fantasy_v1_messages_proto_goTypes = nil
	file_fantasy_v1_messages_proto_depIdxs = nil
}
