// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: fantasy/v1/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WireEnvelope is the binary frame exchanged over WebSocket BinaryMessage
// when the client negotiates codec=protobuf.
type WireEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireEnvelope) Reset() {
	*x = WireEnvelope{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireEnvelope) ProtoMessage() {}

func (x *WireEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireEnvelope.ProtoReflect.Descriptor instead.
func (*WireEnvelope) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *WireEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WireEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JoinWorldPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Race          string                 `protobuf:"bytes,2,opt,name=race,proto3" json:"race,omitempty"`
	MainJob       string                 `protobuf:"bytes,3,opt,name=main_job,json=mainJob,proto3" json:"main_job,omitempty"`
	SubJob        string                 `protobuf:"bytes,4,opt,name=sub_job,json=subJob,proto3" json:"sub_job,omitempty"`
	Job           string                 `protobuf:"bytes,5,opt,name=job,proto3" json:"job,omitempty"`
	Weapon        string                 `protobuf:"bytes,6,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Appearance    *CharacterAppearance   `protobuf:"bytes,7,opt,name=appearance,proto3" json:"appearance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinWorldPayload) Reset() {
	*x = JoinWorldPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinWorldPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldPayload) ProtoMessage() {}

func (x *JoinWorldPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldPayload.ProtoReflect.Descriptor instead.
func (*JoinWorldPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *JoinWorldPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *JoinWorldPayload) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

func (x *JoinWorldPayload) GetMainJob() string {
	if x != nil {
		return x.MainJob
	}
	return ""
}

func (x *JoinWorldPayload) GetSubJob() string {
	if x != nil {
		return x.SubJob
	}
	return ""
}

func (x *JoinWorldPayload) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *JoinWorldPayload) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *JoinWorldPayload) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

type MovePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePayload) Reset() {
	*x = MovePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePayload) ProtoMessage() {}

func (x *MovePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePayload.ProtoReflect.Descriptor instead.
func (*MovePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MovePayload) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MovePayload) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ChatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPayload) Reset() {
	*x = ChatPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPayload) ProtoMessage() {}

func (x *ChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPayload.ProtoReflect.Descriptor instead.
func (*ChatPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ChatPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EquipPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Slot          string                 `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipPayload) Reset() {
	*x = EquipPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipPayload) ProtoMessage() {}

func (x *EquipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipPayload.ProtoReflect.Descriptor instead.
func (*EquipPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *EquipPayload) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *EquipPayload) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type UnequipPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipPayload) Reset() {
	*x = UnequipPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipPayload) ProtoMessage() {}

func (x *UnequipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipPayload.ProtoReflect.Descriptor instead.
func (*UnequipPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UnequipPayload) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type SetJobsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainJob       string                 `protobuf:"bytes,1,opt,name=main_job,json=mainJob,proto3" json:"main_job,omitempty"`
	SubJob        string                 `protobuf:"bytes,2,opt,name=sub_job,json=subJob,proto3" json:"sub_job,omitempty"`
	JobChangerId  string                 `protobuf:"bytes,3,opt,name=job_changer_id,json=jobChangerId,proto3" json:"job_changer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobsPayload) Reset() {
	*x = SetJobsPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobsPayload) ProtoMessage() {}

func (x *SetJobsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobsPayload.ProtoReflect.Descriptor instead.
func (*SetJobsPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SetJobsPayload) GetMainJob() string {
	if x != nil {
		return x.MainJob
	}
	return ""
}

func (x *SetJobsPayload) GetSubJob() string {
	if x != nil {
		return x.SubJob
	}
	return ""
}

func (x *SetJobsPayload) GetJobChangerId() string {
	if x != nil {
		return x.JobChangerId
	}
	return ""
}

type SetHotbarPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHotbarPayload) Reset() {
	*x = SetHotbarPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHotbarPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHotbarPayload) ProtoMessage() {}

func (x *SetHotbarPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHotbarPayload.ProtoReflect.Descriptor instead.
func (*SetHotbarPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SetHotbarPayload) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *SetHotbarPayload) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SetHotbarPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetKeybindsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keybinds      map[string]string      `protobuf:"bytes,1,rep,name=keybinds,proto3" json:"keybinds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeybindsPayload) Reset() {
	*x = SetKeybindsPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeybindsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeybindsPayload) ProtoMessage() {}

func (x *SetKeybindsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeybindsPayload.ProtoReflect.Descriptor instead.
func (*SetKeybindsPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SetKeybindsPayload) GetKeybinds() map[string]string {
	if x != nil {
		return x.Keybinds
	}
	return nil
}

type PlayerNamePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerNamePayload) Reset() {
	*x = PlayerNamePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerNamePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerNamePayload) ProtoMessage() {}

func (x *PlayerNamePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerNamePayload.ProtoReflect.Descriptor instead.
func (*PlayerNamePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerNamePayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type PartyKickPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyKickPayload) Reset() {
	*x = PartyKickPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyKickPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyKickPayload) ProtoMessage() {}

func (x *PartyKickPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyKickPayload.ProtoReflect.Descriptor instead.
func (*PartyKickPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PartyKickPayload) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type JoinBattlePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattlePayload) Reset() {
	*x = JoinBattlePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattlePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattlePayload) ProtoMessage() {}

func (x *JoinBattlePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattlePayload.ProtoReflect.Descriptor instead.
func (*JoinBattlePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *JoinBattlePayload) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type ActionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionPayload) Reset() {
	*x = ActionPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionPayload) ProtoMessage() {}

func (x *ActionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionPayload.ProtoReflect.Descriptor instead.
func (*ActionPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ActionPayload) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ActionPayload) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type SetTargetPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTargetPayload) Reset() {
	*x = SetTargetPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetPayload) ProtoMessage() {}

func (x *SetTargetPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetPayload.ProtoReflect.Descriptor instead.
func (*SetTargetPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *SetTargetPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type SetSavePointPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavePointId   string                 `protobuf:"bytes,1,opt,name=save_point_id,json=savePointId,proto3" json:"save_point_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSavePointPayload) Reset() {
	*x = SetSavePointPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSavePointPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSavePointPayload) ProtoMessage() {}

func (x *SetSavePointPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSavePointPayload.ProtoReflect.Descriptor instead.
func (*SetSavePointPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SetSavePointPayload) GetSavePointId() string {
	if x != nil {
		return x.SavePointId
	}
	return ""
}

type UseWorldSkillPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	SavePointId   string                 `protobuf:"bytes,2,opt,name=save_point_id,json=savePointId,proto3" json:"save_point_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseWorldSkillPayload) Reset() {
	*x = UseWorldSkillPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseWorldSkillPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseWorldSkillPayload) ProtoMessage() {}

func (x *UseWorldSkillPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseWorldSkillPayload.ProtoReflect.Descriptor instead.
func (*UseWorldSkillPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *UseWorldSkillPayload) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *UseWorldSkillPayload) GetSavePointId() string {
	if x != nil {
		return x.SavePointId
	}
	return ""
}

type RTMovePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTMovePayload) Reset() {
	*x = RTMovePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTMovePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTMovePayload) ProtoMessage() {}

func (x *RTMovePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTMovePayload.ProtoReflect.Descriptor instead.
func (*RTMovePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *RTMovePayload) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RTMovePayload) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RTAttackPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacingX       float64                `protobuf:"fixed64,1,opt,name=facing_x,json=facingX,proto3" json:"facing_x,omitempty"`
	FacingY       float64                `protobuf:"fixed64,2,opt,name=facing_y,json=facingY,proto3" json:"facing_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTAttackPayload) Reset() {
	*x = RTAttackPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTAttackPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTAttackPayload) ProtoMessage() {}

func (x *RTAttackPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTAttackPayload.ProtoReflect.Descriptor instead.
func (*RTAttackPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *RTAttackPayload) GetFacingX() float64 {
	if x != nil {
		return x.FacingX
	}
	return 0
}

func (x *RTAttackPayload) GetFacingY() float64 {
	if x != nil {
		return x.FacingY
	}
	return 0
}

type WelcomePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Profile       *ProfileInfo           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Map           *MapSnapshot           `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomePayload) Reset() {
	*x = WelcomePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePayload) ProtoMessage() {}

func (x *WelcomePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePayload.ProtoReflect.Descriptor instead.
func (*WelcomePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *WelcomePayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *WelcomePayload) GetProfile() *ProfileInfo {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *WelcomePayload) GetMap() *MapSnapshot {
	if x != nil {
		return x.Map
	}
	return nil
}

type MapConfigPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           *MapSnapshot           `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapConfigPayload) Reset() {
	*x = MapConfigPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapConfigPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapConfigPayload) ProtoMessage() {}

func (x *MapConfigPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapConfigPayload.ProtoReflect.Descriptor instead.
func (*MapConfigPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *MapConfigPayload) GetMap() *MapSnapshot {
	if x != nil {
		return x.Map
	}
	return nil
}

type WorldStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*WorldPlayer         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Npcs          []*WorldNPC            `protobuf:"bytes,2,rep,name=npcs,proto3" json:"npcs,omitempty"`
	Battles       []*BattleInfo          `protobuf:"bytes,3,rep,name=battles,proto3" json:"battles,omitempty"`
	SavePoints    []*SavePoint           `protobuf:"bytes,4,rep,name=save_points,json=savePoints,proto3" json:"save_points,omitempty"`
	JobChangers   []*JobChanger          `protobuf:"bytes,5,rep,name=job_changers,json=jobChangers,proto3" json:"job_changers,omitempty"`
	Map           *OverworldMap          `protobuf:"bytes,6,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldStatePayload) Reset() {
	*x = WorldStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldStatePayload) ProtoMessage() {}

func (x *WorldStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldStatePayload.ProtoReflect.Descriptor instead.
func (*WorldStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *WorldStatePayload) GetPlayers() []*WorldPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldStatePayload) GetNpcs() []*WorldNPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *WorldStatePayload) GetBattles() []*BattleInfo {
	if x != nil {
		return x.Battles
	}
	return nil
}

func (x *WorldStatePayload) GetSavePoints() []*SavePoint {
	if x != nil {
		return x.SavePoints
	}
	return nil
}

func (x *WorldStatePayload) GetJobChangers() []*JobChanger {
	if x != nil {
		return x.JobChangers
	}
	return nil
}

func (x *WorldStatePayload) GetMap() *OverworldMap {
	if x != nil {
		return x.Map
	}
	return nil
}

type PlayerLeftPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeftPayload) Reset() {
	*x = PlayerLeftPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftPayload) ProtoMessage() {}

func (x *PlayerLeftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftPayload.ProtoReflect.Descriptor instead.
func (*PlayerLeftPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerLeftPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlayerMovedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMovedPayload) Reset() {
	*x = PlayerMovedPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMovedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMovedPayload) ProtoMessage() {}

func (x *PlayerMovedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMovedPayload.ProtoReflect.Descriptor instead.
func (*PlayerMovedPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerMovedPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerMovedPayload) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMovedPayload) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ChatMessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessagePayload) Reset() {
	*x = ChatMessagePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessagePayload) ProtoMessage() {}

func (x *ChatMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessagePayload.ProtoReflect.Descriptor instead.
func (*ChatMessagePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{23}
}

func (x *ChatMessagePayload) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *ChatMessagePayload) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *ChatMessagePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessagePayload) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type NPCStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Npcs          []*WorldNPC            `protobuf:"bytes,1,rep,name=npcs,proto3" json:"npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NPCStatePayload) Reset() {
	*x = NPCStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPCStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPCStatePayload) ProtoMessage() {}

func (x *NPCStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPCStatePayload.ProtoReflect.Descriptor instead.
func (*NPCStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{24}
}

func (x *NPCStatePayload) GetNpcs() []*WorldNPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

type BattleListPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Battles       []*BattleInfo          `protobuf:"bytes,1,rep,name=battles,proto3" json:"battles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleListPayload) Reset() {
	*x = BattleListPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleListPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleListPayload) ProtoMessage() {}

func (x *BattleListPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleListPayload.ProtoReflect.Descriptor instead.
func (*BattleListPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{25}
}

func (x *BattleListPayload) GetBattles() []*BattleInfo {
	if x != nil {
		return x.Battles
	}
	return nil
}

type BattleStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Entities      []*BattleEntity        `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	BattleSpeed   float64                `protobuf:"fixed64,3,opt,name=battle_speed,json=battleSpeed,proto3" json:"battle_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStatePayload) Reset() {
	*x = BattleStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStatePayload) ProtoMessage() {}

func (x *BattleStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStatePayload.ProtoReflect.Descriptor instead.
func (*BattleStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{26}
}

func (x *BattleStatePayload) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleStatePayload) GetEntities() []*BattleEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *BattleStatePayload) GetBattleSpeed() float64 {
	if x != nil {
		return x.BattleSpeed
	}
	return 0
}

type BattleEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ActionResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Entities      []*EntityUpdate        `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEventPayload) Reset() {
	*x = BattleEventPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEventPayload) ProtoMessage() {}

func (x *BattleEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEventPayload.ProtoReflect.Descriptor instead.
func (*BattleEventPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{27}
}

func (x *BattleEventPayload) GetResults() []*ActionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BattleEventPayload) GetEntities() []*EntityUpdate {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *BattleEventPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BattleTickPayload struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SkillAtb map[string]float64     `protobuf:"bytes,1,rep,name=skill_atb,json=skillAtb,proto3" json:"skill_atb,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Atb      map[string]float64     `protobuf:"bytes,2,rep,name=atb,proto3" json:"atb,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Hp       map[string]int32       `protobuf:"bytes,3,rep,name=hp,proto3" json:"hp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Alive    map[string]bool        `protobuf:"bytes,4,rep,name=alive,proto3" json:"alive,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// map[string][]StatusSnapshot — encoded as Struct for JSON round-trip.
	Statuses       *structpb.Struct   `protobuf:"bytes,5,opt,name=statuses,proto3" json:"statuses,omitempty"`
	CastingSkillId map[string]string  `protobuf:"bytes,6,rep,name=casting_skill_id,json=castingSkillId,proto3" json:"casting_skill_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CastTargetId   map[string]string  `protobuf:"bytes,7,rep,name=cast_target_id,json=castTargetId,proto3" json:"cast_target_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CastProgress   map[string]float64 `protobuf:"bytes,8,rep,name=cast_progress,json=castProgress,proto3" json:"cast_progress,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	CastTimeMs     map[string]int32   `protobuf:"bytes,9,rep,name=cast_time_ms,json=castTimeMs,proto3" json:"cast_time_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BattleTickPayload) Reset() {
	*x = BattleTickPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleTickPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleTickPayload) ProtoMessage() {}

func (x *BattleTickPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleTickPayload.ProtoReflect.Descriptor instead.
func (*BattleTickPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{28}
}

func (x *BattleTickPayload) GetSkillAtb() map[string]float64 {
	if x != nil {
		return x.SkillAtb
	}
	return nil
}

func (x *BattleTickPayload) GetAtb() map[string]float64 {
	if x != nil {
		return x.Atb
	}
	return nil
}

func (x *BattleTickPayload) GetHp() map[string]int32 {
	if x != nil {
		return x.Hp
	}
	return nil
}

func (x *BattleTickPayload) GetAlive() map[string]bool {
	if x != nil {
		return x.Alive
	}
	return nil
}

func (x *BattleTickPayload) GetStatuses() *structpb.Struct {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *BattleTickPayload) GetCastingSkillId() map[string]string {
	if x != nil {
		return x.CastingSkillId
	}
	return nil
}

func (x *BattleTickPayload) GetCastTargetId() map[string]string {
	if x != nil {
		return x.CastTargetId
	}
	return nil
}

func (x *BattleTickPayload) GetCastProgress() map[string]float64 {
	if x != nil {
		return x.CastProgress
	}
	return nil
}

func (x *BattleTickPayload) GetCastTimeMs() map[string]int32 {
	if x != nil {
		return x.CastTimeMs
	}
	return nil
}

type BattleEndPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Victory       bool                   `protobuf:"varint,1,opt,name=victory,proto3" json:"victory,omitempty"`
	Rewards       []*PlayerReward        `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEndPayload) Reset() {
	*x = BattleEndPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEndPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEndPayload) ProtoMessage() {}

func (x *BattleEndPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEndPayload.ProtoReflect.Descriptor instead.
func (*BattleEndPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{29}
}

func (x *BattleEndPayload) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *BattleEndPayload) GetRewards() []*PlayerReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type PartyInvitePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	PartyId       string                 `protobuf:"bytes,3,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInvitePayload) Reset() {
	*x = PartyInvitePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInvitePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInvitePayload) ProtoMessage() {}

func (x *PartyInvitePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInvitePayload.ProtoReflect.Descriptor instead.
func (*PartyInvitePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{30}
}

func (x *PartyInvitePayload) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *PartyInvitePayload) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *PartyInvitePayload) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type BattleInvitePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,3,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleInvitePayload) Reset() {
	*x = BattleInvitePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleInvitePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleInvitePayload) ProtoMessage() {}

func (x *BattleInvitePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleInvitePayload.ProtoReflect.Descriptor instead.
func (*BattleInvitePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{31}
}

func (x *BattleInvitePayload) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleInvitePayload) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *BattleInvitePayload) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

type FriendRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestPayload) Reset() {
	*x = FriendRequestPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestPayload) ProtoMessage() {}

func (x *FriendRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestPayload.ProtoReflect.Descriptor instead.
func (*FriendRequestPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{32}
}

func (x *FriendRequestPayload) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *FriendRequestPayload) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

type RewardNoticePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xp            int32                  `protobuf:"varint,1,opt,name=xp,proto3" json:"xp,omitempty"`
	Passive       bool                   `protobuf:"varint,2,opt,name=passive,proto3" json:"passive,omitempty"`
	Victory       bool                   `protobuf:"varint,3,opt,name=victory,proto3" json:"victory,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardNoticePayload) Reset() {
	*x = RewardNoticePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardNoticePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardNoticePayload) ProtoMessage() {}

func (x *RewardNoticePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardNoticePayload.ProtoReflect.Descriptor instead.
func (*RewardNoticePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{33}
}

func (x *RewardNoticePayload) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *RewardNoticePayload) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *RewardNoticePayload) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *RewardNoticePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SocialStatePayload struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Friends                []*FriendInfo           `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Party                  *PartyInfo              `protobuf:"bytes,2,opt,name=party,proto3" json:"party,omitempty"`
	PendingInvite          *PartyInvitePayload     `protobuf:"bytes,3,opt,name=pending_invite,json=pendingInvite,proto3" json:"pending_invite,omitempty"`
	PendingFriendRequests  []*FriendRequestPayload `protobuf:"bytes,4,rep,name=pending_friend_requests,json=pendingFriendRequests,proto3" json:"pending_friend_requests,omitempty"`
	OutgoingFriendRequests []string                `protobuf:"bytes,5,rep,name=outgoing_friend_requests,json=outgoingFriendRequests,proto3" json:"outgoing_friend_requests,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SocialStatePayload) Reset() {
	*x = SocialStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialStatePayload) ProtoMessage() {}

func (x *SocialStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialStatePayload.ProtoReflect.Descriptor instead.
func (*SocialStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{34}
}

func (x *SocialStatePayload) GetFriends() []*FriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *SocialStatePayload) GetParty() *PartyInfo {
	if x != nil {
		return x.Party
	}
	return nil
}

func (x *SocialStatePayload) GetPendingInvite() *PartyInvitePayload {
	if x != nil {
		return x.PendingInvite
	}
	return nil
}

func (x *SocialStatePayload) GetPendingFriendRequests() []*FriendRequestPayload {
	if x != nil {
		return x.PendingFriendRequests
	}
	return nil
}

func (x *SocialStatePayload) GetOutgoingFriendRequests() []string {
	if x != nil {
		return x.OutgoingFriendRequests
	}
	return nil
}

type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{35}
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RTBattleStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Entities      []*RTBattleEntity      `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTBattleStatePayload) Reset() {
	*x = RTBattleStatePayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTBattleStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTBattleStatePayload) ProtoMessage() {}

func (x *RTBattleStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTBattleStatePayload.ProtoReflect.Descriptor instead.
func (*RTBattleStatePayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{36}
}

func (x *RTBattleStatePayload) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *RTBattleStatePayload) GetEntities() []*RTBattleEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *RTBattleStatePayload) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type RTBattleTickPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*RTBattleEntity      `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTBattleTickPayload) Reset() {
	*x = RTBattleTickPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTBattleTickPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTBattleTickPayload) ProtoMessage() {}

func (x *RTBattleTickPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTBattleTickPayload.ProtoReflect.Descriptor instead.
func (*RTBattleTickPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{37}
}

func (x *RTBattleTickPayload) GetEntities() []*RTBattleEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type RTBattleEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    string                 `protobuf:"bytes,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	Heal          int32                  `protobuf:"varint,4,opt,name=heal,proto3" json:"heal,omitempty"`
	MpRestored    int32                  `protobuf:"varint,5,opt,name=mp_restored,json=mpRestored,proto3" json:"mp_restored,omitempty"`
	Hit           bool                   `protobuf:"varint,6,opt,name=hit,proto3" json:"hit,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	ActionId      string                 `protobuf:"bytes,8,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionName    string                 `protobuf:"bytes,9,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Success       bool                   `protobuf:"varint,10,opt,name=success,proto3" json:"success,omitempty"`
	CastStarted   bool                   `protobuf:"varint,11,opt,name=cast_started,json=castStarted,proto3" json:"cast_started,omitempty"`
	CastCancelled bool                   `protobuf:"varint,12,opt,name=cast_cancelled,json=castCancelled,proto3" json:"cast_cancelled,omitempty"`
	Entities      []*RTBattleEntity      `protobuf:"bytes,13,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTBattleEventPayload) Reset() {
	*x = RTBattleEventPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTBattleEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTBattleEventPayload) ProtoMessage() {}

func (x *RTBattleEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTBattleEventPayload.ProtoReflect.Descriptor instead.
func (*RTBattleEventPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{38}
}

func (x *RTBattleEventPayload) GetAttackerId() string {
	if x != nil {
		return x.AttackerId
	}
	return ""
}

func (x *RTBattleEventPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RTBattleEventPayload) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *RTBattleEventPayload) GetHeal() int32 {
	if x != nil {
		return x.Heal
	}
	return 0
}

func (x *RTBattleEventPayload) GetMpRestored() int32 {
	if x != nil {
		return x.MpRestored
	}
	return 0
}

func (x *RTBattleEventPayload) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *RTBattleEventPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RTBattleEventPayload) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *RTBattleEventPayload) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *RTBattleEventPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RTBattleEventPayload) GetCastStarted() bool {
	if x != nil {
		return x.CastStarted
	}
	return false
}

func (x *RTBattleEventPayload) GetCastCancelled() bool {
	if x != nil {
		return x.CastCancelled
	}
	return false
}

func (x *RTBattleEventPayload) GetEntities() []*RTBattleEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type RTBattleEndPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Victory       bool                   `protobuf:"varint,1,opt,name=victory,proto3" json:"victory,omitempty"`
	Rewards       []*PlayerReward        `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTBattleEndPayload) Reset() {
	*x = RTBattleEndPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTBattleEndPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTBattleEndPayload) ProtoMessage() {}

func (x *RTBattleEndPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTBattleEndPayload.ProtoReflect.Descriptor instead.
func (*RTBattleEndPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{39}
}

func (x *RTBattleEndPayload) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *RTBattleEndPayload) GetRewards() []*PlayerReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// EmptyPayload covers leave_battle, party_accept, etc.
type EmptyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyPayload) Reset() {
	*x = EmptyPayload{}
	mi := &file_fantasy_v1_messages_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyPayload) ProtoMessage() {}

func (x *EmptyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fantasy_v1_messages_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyPayload.ProtoReflect.Descriptor instead.
func (*EmptyPayload) Descriptor() ([]byte, []int) {
	return file_fantasy_v1_messages_proto_rawDescGZIP(), []int{40}
}

var File_fantasy_v1_messages_proto protoreflect.FileDescriptor

const file_fantasy_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x19fantasy/v1/messages.proto\x12\n" +
	"fantasy.v1\x1a\x17fantasy/v1/common.proto\x1a\x1cgoogle/protobuf/struct.proto\"<\n" +
	"\fWireEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xe6\x01\n" +
	"\x10JoinWorldPayload\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x12\n" +
	"\x04race\x18\x02 \x01(\tR\x04race\x12\x19\n" +
	"\bmain_job\x18\x03 \x01(\tR\amainJob\x12\x17\n" +
	"\asub_job\x18\x04 \x01(\tR\x06subJob\x12\x10\n" +
	"\x03job\x18\x05 \x01(\tR\x03job\x12\x16\n" +
	"\x06weapon\x18\x06 \x01(\tR\x06weapon\x12?\n" +
	"\n" +
	"appearance\x18\a \x01(\v2\x1f.fantasy.v1.CharacterAppearanceR\n" +
	"appearance\")\n" +
	"\vMovePayload\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"'\n" +
	"\vChatPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\fEquipPayload\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\tR\x04slot\"$\n" +
	"\x0eUnequipPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"j\n" +
	"\x0eSetJobsPayload\x12\x19\n" +
	"\bmain_job\x18\x01 \x01(\tR\amainJob\x12\x17\n" +
	"\asub_job\x18\x02 \x01(\tR\x06subJob\x12$\n" +
	"\x0ejob_changer_id\x18\x03 \x01(\tR\fjobChangerId\"J\n" +
	"\x10SetHotbarPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\x9b\x01\n" +
	"\x12SetKeybindsPayload\x12H\n" +
	"\bkeybinds\x18\x01 \x03(\v2,.fantasy.v1.SetKeybindsPayload.KeybindsEntryR\bkeybinds\x1a;\n" +
	"\rKeybindsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11PlayerNamePayload\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"/\n" +
	"\x10PartyKickPayload\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"0\n" +
	"\x11JoinBattlePayload\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"b\n" +
	"\rActionPayload\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\"/\n" +
	"\x10SetTargetPayload\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"9\n" +
	"\x13SetSavePointPayload\x12\"\n" +
	"\rsave_point_id\x18\x01 \x01(\tR\vsavePointId\"U\n" +
	"\x14UseWorldSkillPayload\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\"\n" +
	"\rsave_point_id\x18\x02 \x01(\tR\vsavePointId\"+\n" +
	"\rRTMovePayload\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"G\n" +
	"\x0fRTAttackPayload\x12\x19\n" +
	"\bfacing_x\x18\x01 \x01(\x01R\afacingX\x12\x19\n" +
	"\bfacing_y\x18\x02 \x01(\x01R\afacingY\"\x8b\x01\n" +
	"\x0eWelcomePayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x121\n" +
	"\aprofile\x18\x02 \x01(\v2\x17.fantasy.v1.ProfileInfoR\aprofile\x12)\n" +
	"\x03map\x18\x03 \x01(\v2\x17.fantasy.v1.MapSnapshotR\x03map\"=\n" +
	"\x10MapConfigPayload\x12)\n" +
	"\x03map\x18\x01 \x01(\v2\x17.fantasy.v1.MapSnapshotR\x03map\"\xc1\x02\n" +
	"\x11WorldStatePayload\x121\n" +
	"\aplayers\x18\x01 \x03(\v2\x17.fantasy.v1.WorldPlayerR\aplayers\x12(\n" +
	"\x04npcs\x18\x02 \x03(\v2\x14.fantasy.v1.WorldNPCR\x04npcs\x120\n" +
	"\abattles\x18\x03 \x03(\v2\x16.fantasy.v1.BattleInfoR\abattles\x126\n" +
	"\vsave_points\x18\x04 \x03(\v2\x15.fantasy.v1.SavePointR\n" +
	"savePoints\x129\n" +
	"\fjob_changers\x18\x05 \x03(\v2\x16.fantasy.v1.JobChangerR\vjobChangers\x12*\n" +
	"\x03map\x18\x06 \x01(\v2\x18.fantasy.v1.OverworldMapR\x03map\"#\n" +
	"\x11PlayerLeftPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12PlayerMovedPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\"~\n" +
	"\x12ChatMessagePayload\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\";\n" +
	"\x0fNPCStatePayload\x12(\n" +
	"\x04npcs\x18\x01 \x03(\v2\x14.fantasy.v1.WorldNPCR\x04npcs\"E\n" +
	"\x11BattleListPayload\x120\n" +
	"\abattles\x18\x01 \x03(\v2\x16.fantasy.v1.BattleInfoR\abattles\"\x8a\x01\n" +
	"\x12BattleStatePayload\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x124\n" +
	"\bentities\x18\x02 \x03(\v2\x18.fantasy.v1.BattleEntityR\bentities\x12!\n" +
	"\fbattle_speed\x18\x03 \x01(\x01R\vbattleSpeed\"\x9c\x01\n" +
	"\x12BattleEventPayload\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.fantasy.v1.ActionResultR\aresults\x124\n" +
	"\bentities\x18\x02 \x03(\v2\x18.fantasy.v1.EntityUpdateR\bentities\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x88\t\n" +
	"\x11BattleTickPayload\x12H\n" +
	"\tskill_atb\x18\x01 \x03(\v2+.fantasy.v1.BattleTickPayload.SkillAtbEntryR\bskillAtb\x128\n" +
	"\x03atb\x18\x02 \x03(\v2&.fantasy.v1.BattleTickPayload.AtbEntryR\x03atb\x125\n" +
	"\x02hp\x18\x03 \x03(\v2%.fantasy.v1.BattleTickPayload.HpEntryR\x02hp\x12>\n" +
	"\x05alive\x18\x04 \x03(\v2(.fantasy.v1.BattleTickPayload.AliveEntryR\x05alive\x123\n" +
	"\bstatuses\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bstatuses\x12[\n" +
	"\x10casting_skill_id\x18\x06 \x03(\v21.fantasy.v1.BattleTickPayload.CastingSkillIdEntryR\x0ecastingSkillId\x12U\n" +
	"\x0ecast_target_id\x18\a \x03(\v2/.fantasy.v1.BattleTickPayload.CastTargetIdEntryR\fcastTargetId\x12T\n" +
	"\rcast_progress\x18\b \x03(\v2/.fantasy.v1.BattleTickPayload.CastProgressEntryR\fcastProgress\x12O\n" +
	"\fcast_time_ms\x18\t \x03(\v2-.fantasy.v1.BattleTickPayload.CastTimeMsEntryR\n" +
	"castTimeMs\x1a;\n" +
	"\rSkillAtbEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a6\n" +
	"\bAtbEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a5\n" +
	"\aHpEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"AliveEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aA\n" +
	"\x13CastingSkillIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11CastTargetIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11CastProgressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fCastTimeMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"`\n" +
	"\x10BattleEndPayload\x12\x18\n" +
	"\avictory\x18\x01 \x01(\bR\avictory\x122\n" +
	"\arewards\x18\x02 \x03(\v2\x18.fantasy.v1.PlayerRewardR\arewards\"e\n" +
	"\x12PartyInvitePayload\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\x12\x19\n" +
	"\bparty_id\x18\x03 \x01(\tR\apartyId\"h\n" +
	"\x13BattleInvitePayload\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x03 \x01(\tR\bfromName\"L\n" +
	"\x14FriendRequestPayload\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\"s\n" +
	"\x13RewardNoticePayload\x12\x0e\n" +
	"\x02xp\x18\x01 \x01(\x05R\x02xp\x12\x18\n" +
	"\apassive\x18\x02 \x01(\bR\apassive\x12\x18\n" +
	"\avictory\x18\x03 \x01(\bR\avictory\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xce\x02\n" +
	"\x12SocialStatePayload\x120\n" +
	"\afriends\x18\x01 \x03(\v2\x16.fantasy.v1.FriendInfoR\afriends\x12+\n" +
	"\x05party\x18\x02 \x01(\v2\x15.fantasy.v1.PartyInfoR\x05party\x12E\n" +
	"\x0epending_invite\x18\x03 \x01(\v2\x1e.fantasy.v1.PartyInvitePayloadR\rpendingInvite\x12X\n" +
	"\x17pending_friend_requests\x18\x04 \x03(\v2 .fantasy.v1.FriendRequestPayloadR\x15pendingFriendRequests\x128\n" +
	"\x18outgoing_friend_requests\x18\x05 \x03(\tR\x16outgoingFriendRequests\"(\n" +
	"\fErrorPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x7f\n" +
	"\x14RTBattleStatePayload\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x126\n" +
	"\bentities\x18\x02 \x03(\v2\x1a.fantasy.v1.RTBattleEntityR\bentities\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"M\n" +
	"\x13RTBattleTickPayload\x126\n" +
	"\bentities\x18\x01 \x03(\v2\x1a.fantasy.v1.RTBattleEntityR\bentities\"\xa7\x03\n" +
	"\x14RTBattleEventPayload\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\tR\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12\x12\n" +
	"\x04heal\x18\x04 \x01(\x05R\x04heal\x12\x1f\n" +
	"\vmp_restored\x18\x05 \x01(\x05R\n" +
	"mpRestored\x12\x10\n" +
	"\x03hit\x18\x06 \x01(\bR\x03hit\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1b\n" +
	"\taction_id\x18\b \x01(\tR\bactionId\x12\x1f\n" +
	"\vaction_name\x18\t \x01(\tR\n" +
	"actionName\x12\x18\n" +
	"\asuccess\x18\n" +
	" \x01(\bR\asuccess\x12!\n" +
	"\fcast_started\x18\v \x01(\bR\vcastStarted\x12%\n" +
	"\x0ecast_cancelled\x18\f \x01(\bR\rcastCancelled\x126\n" +
	"\bentities\x18\r \x03(\v2\x1a.fantasy.v1.RTBattleEntityR\bentities\"b\n" +
	"\x12RTBattleEndPayload\x12\x18\n" +
	"\avictory\x18\x01 \x01(\bR\avictory\x122\n" +
	"\arewards\x18\x02 \x03(\v2\x18.fantasy.v1.PlayerRewardR\arewards\"\x0e\n" +
	"\fEmptyPayloadB#Z!ffv-web-game/internal/protocol/pbb\x06proto3"

var (
	file_fantasy_v1_messages_proto_rawDescOnce sync.Once
	file_fantasy_v1_messages_proto_rawDescData []byte
)

func file_fantasy_v1_messages_proto_rawDescGZIP() []byte {
	file_fantasy_v1_messages_proto_rawDescOnce.Do(func() {
		file_fantasy_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fantasy_v1_messages_proto_rawDesc), len(file_fantasy_v1_messages_proto_rawDesc)))
	})
	return file_fantasy_v1_messages_proto_rawDescData
}

var file_fantasy_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_fantasy_v1_messages_proto_goTypes = []any{
	(*WireEnvelope)(nil),         // 0: fantasy.v1.WireEnvelope
	(*JoinWorldPayload)(nil),     // 1: fantasy.v1.JoinWorldPayload
	(*MovePayload)(nil),          // 2: fantasy.v1.MovePayload
	(*ChatPayload)(nil),          // 3: fantasy.v1.ChatPayload
	(*EquipPayload)(nil),         // 4: fantasy.v1.EquipPayload
	(*UnequipPayload)(nil),       // 5: fantasy.v1.UnequipPayload
	(*SetJobsPayload)(nil),       // 6: fantasy.v1.SetJobsPayload
	(*SetHotbarPayload)(nil),     // 7: fantasy.v1.SetHotbarPayload
	(*SetKeybindsPayload)(nil),   // 8: fantasy.v1.SetKeybindsPayload
	(*PlayerNamePayload)(nil),    // 9: fantasy.v1.PlayerNamePayload
	(*PartyKickPayload)(nil),     // 10: fantasy.v1.PartyKickPayload
	(*JoinBattlePayload)(nil),    // 11: fantasy.v1.JoinBattlePayload
	(*ActionPayload)(nil),        // 12: fantasy.v1.ActionPayload
	(*SetTargetPayload)(nil),     // 13: fantasy.v1.SetTargetPayload
	(*SetSavePointPayload)(nil),  // 14: fantasy.v1.SetSavePointPayload
	(*UseWorldSkillPayload)(nil), // 15: fantasy.v1.UseWorldSkillPayload
	(*RTMovePayload)(nil),        // 16: fantasy.v1.RTMovePayload
	(*RTAttackPayload)(nil),      // 17: fantasy.v1.RTAttackPayload
	(*WelcomePayload)(nil),       // 18: fantasy.v1.WelcomePayload
	(*MapConfigPayload)(nil),     // 19: fantasy.v1.MapConfigPayload
	(*WorldStatePayload)(nil),    // 20: fantasy.v1.WorldStatePayload
	(*PlayerLeftPayload)(nil),    // 21: fantasy.v1.PlayerLeftPayload
	(*PlayerMovedPayload)(nil),   // 22: fantasy.v1.PlayerMovedPayload
	(*ChatMessagePayload)(nil),   // 23: fantasy.v1.ChatMessagePayload
	(*NPCStatePayload)(nil),      // 24: fantasy.v1.NPCStatePayload
	(*BattleListPayload)(nil),    // 25: fantasy.v1.BattleListPayload
	(*BattleStatePayload)(nil),   // 26: fantasy.v1.BattleStatePayload
	(*BattleEventPayload)(nil),   // 27: fantasy.v1.BattleEventPayload
	(*BattleTickPayload)(nil),    // 28: fantasy.v1.BattleTickPayload
	(*BattleEndPayload)(nil),     // 29: fantasy.v1.BattleEndPayload
	(*PartyInvitePayload)(nil),   // 30: fantasy.v1.PartyInvitePayload
	(*BattleInvitePayload)(nil),  // 31: fantasy.v1.BattleInvitePayload
	(*FriendRequestPayload)(nil), // 32: fantasy.v1.FriendRequestPayload
	(*RewardNoticePayload)(nil),  // 33: fantasy.v1.RewardNoticePayload
	(*SocialStatePayload)(nil),   // 34: fantasy.v1.SocialStatePayload
	(*ErrorPayload)(nil),         // 35: fantasy.v1.ErrorPayload
	(*RTBattleStatePayload)(nil), // 36: fantasy.v1.RTBattleStatePayload
	(*RTBattleTickPayload)(nil),  // 37: fantasy.v1.RTBattleTickPayload
	(*RTBattleEventPayload)(nil), // 38: fantasy.v1.RTBattleEventPayload
	(*RTBattleEndPayload)(nil),   // 39: fantasy.v1.RTBattleEndPayload
	(*EmptyPayload)(nil),         // 40: fantasy.v1.EmptyPayload
	nil,                          // 41: fantasy.v1.SetKeybindsPayload.KeybindsEntry
	nil,                          // 42: fantasy.v1.BattleTickPayload.SkillAtbEntry
	nil,                          // 43: fantasy.v1.BattleTickPayload.AtbEntry
	nil,                          // 44: fantasy.v1.BattleTickPayload.HpEntry
	nil,                          // 45: fantasy.v1.BattleTickPayload.AliveEntry
	nil,                          // 46: fantasy.v1.BattleTickPayload.CastingSkillIdEntry
	nil,                          // 47: fantasy.v1.BattleTickPayload.CastTargetIdEntry
	nil,                          // 48: fantasy.v1.BattleTickPayload.CastProgressEntry
	nil,                          // 49: fantasy.v1.BattleTickPayload.CastTimeMsEntry
	(*CharacterAppearance)(nil),  // 50: fantasy.v1.CharacterAppearance
	(*ProfileInfo)(nil),          // 51: fantasy.v1.ProfileInfo
	(*MapSnapshot)(nil),          // 52: fantasy.v1.MapSnapshot
	(*WorldPlayer)(nil),          // 53: fantasy.v1.WorldPlayer
	(*WorldNPC)(nil),             // 54: fantasy.v1.WorldNPC
	(*BattleInfo)(nil),           // 55: fantasy.v1.BattleInfo
	(*SavePoint)(nil),            // 56: fantasy.v1.SavePoint
	(*JobChanger)(nil),           // 57: fantasy.v1.JobChanger
	(*OverworldMap)(nil),         // 58: fantasy.v1.OverworldMap
	(*BattleEntity)(nil),         // 59: fantasy.v1.BattleEntity
	(*ActionResult)(nil),         // 60: fantasy.v1.ActionResult
	(*EntityUpdate)(nil),         // 61: fantasy.v1.EntityUpdate
	(*structpb.Struct)(nil),      // 62: google.protobuf.Struct
	(*PlayerReward)(nil),         // 63: fantasy.v1.PlayerReward
	(*FriendInfo)(nil),           // 64: fantasy.v1.FriendInfo
	(*PartyInfo)(nil),            // 65: fantasy.v1.PartyInfo
	(*RTBattleEntity)(nil),       // 66: fantasy.v1.RTBattleEntity
}
var file_fantasy_v1_messages_proto_depIdxs = []int32{
	50, // 0: fantasy.v1.JoinWorldPayload.appearance:type_name -> fantasy.v1.CharacterAppearance
	41, // 1: fantasy.v1.SetKeybindsPayload.keybinds:type_name -> fantasy.v1.SetKeybindsPayload.KeybindsEntry
	51, // 2: fantasy.v1.WelcomePayload.profile:type_name -> fantasy.v1.ProfileInfo
	52, // 3: fantasy.v1.WelcomePayload.map:type_name -> fantasy.v1.MapSnapshot
	52, // 4: fantasy.v1.MapConfigPayload.map:type_name -> fantasy.v1.MapSnapshot
	53, // 5: fantasy.v1.WorldStatePayload.players:type_name -> fantasy.v1.WorldPlayer
	54, // 6: fantasy.v1.WorldStatePayload.npcs:type_name -> fantasy.v1.WorldNPC
	55, // 7: fantasy.v1.WorldStatePayload.battles:type_name -> fantasy.v1.BattleInfo
	56, // 8: fantasy.v1.WorldStatePayload.save_points:type_name -> fantasy.v1.SavePoint
	57, // 9: fantasy.v1.WorldStatePayload.job_changers:type_name -> fantasy.v1.JobChanger
	58, // 10: fantasy.v1.WorldStatePayload.map:type_name -> fantasy.v1.OverworldMap
	54, // 11: fantasy.v1.NPCStatePayload.npcs:type_name -> fantasy.v1.WorldNPC
	55, // 12: fantasy.v1.BattleListPayload.battles:type_name -> fantasy.v1.BattleInfo
	59, // 13: fantasy.v1.BattleStatePayload.entities:type_name -> fantasy.v1.BattleEntity
	60, // 14: fantasy.v1.BattleEventPayload.results:type_name -> fantasy.v1.ActionResult
	61, // 15: fantasy.v1.BattleEventPayload.entities:type_name -> fantasy.v1.EntityUpdate
	42, // 16: fantasy.v1.BattleTickPayload.skill_atb:type_name -> fantasy.v1.BattleTickPayload.SkillAtbEntry
	43, // 17: fantasy.v1.BattleTickPayload.atb:type_name -> fantasy.v1.BattleTickPayload.AtbEntry
	44, // 18: fantasy.v1.BattleTickPayload.hp:type_name -> fantasy.v1.BattleTickPayload.HpEntry
	45, // 19: fantasy.v1.BattleTickPayload.alive:type_name -> fantasy.v1.BattleTickPayload.AliveEntry
	62, // 20: fantasy.v1.BattleTickPayload.statuses:type_name -> google.protobuf.Struct
	46, // 21: fantasy.v1.BattleTickPayload.casting_skill_id:type_name -> fantasy.v1.BattleTickPayload.CastingSkillIdEntry
	47, // 22: fantasy.v1.BattleTickPayload.cast_target_id:type_name -> fantasy.v1.BattleTickPayload.CastTargetIdEntry
	48, // 23: fantasy.v1.BattleTickPayload.cast_progress:type_name -> fantasy.v1.BattleTickPayload.CastProgressEntry
	49, // 24: fantasy.v1.BattleTickPayload.cast_time_ms:type_name -> fantasy.v1.BattleTickPayload.CastTimeMsEntry
	63, // 25: fantasy.v1.BattleEndPayload.rewards:type_name -> fantasy.v1.PlayerReward
	64, // 26: fantasy.v1.SocialStatePayload.friends:type_name -> fantasy.v1.FriendInfo
	65, // 27: fantasy.v1.SocialStatePayload.party:type_name -> fantasy.v1.PartyInfo
	30, // 28: fantasy.v1.SocialStatePayload.pending_invite:type_name -> fantasy.v1.PartyInvitePayload
	32, // 29: fantasy.v1.SocialStatePayload.pending_friend_requests:type_name -> fantasy.v1.FriendRequestPayload
	66, // 30: fantasy.v1.RTBattleStatePayload.entities:type_name -> fantasy.v1.RTBattleEntity
	66, // 31: fantasy.v1.RTBattleTickPayload.entities:type_name -> fantasy.v1.RTBattleEntity
	66, // 32: fantasy.v1.RTBattleEventPayload.entities:type_name -> fantasy.v1.RTBattleEntity
	63, // 33: fantasy.v1.RTBattleEndPayload.rewards:type_name -> fantasy.v1.PlayerReward
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_fantasy_v1_messages_proto_init() }
func file_fantasy_v1_messages_proto_init() {
	if File_fantasy_v1_messages_proto != nil {
		return
	}
	file_fantasy_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fantasy_v1_messages_proto_rawDesc), len(file_fantasy_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fantasy_v1_messages_proto_goTypes,
		DependencyIndexes: file_fantasy_v1_messages_proto_depIdxs,
		MessageInfos:      file_fantasy_v1_messages_proto_msgTypes,
	}.Build()
	File_fantasy_v1_messages_proto = out.File
	file_fantasy_v1_messages_proto_goTypes = nil
	file_fantasy_v1_messages_proto_depIdxs = nil
}
