// Command genwire emits TypeScript wire types for the client by parsing the
// Go structs in internal/protocol (and any internal/game types they
// reference). It writes wails/frontend/src/net/wire.gen.ts; src/types.ts
// re-exports it, so wire shapes have a single source of truth: messages.go.
//
// Run: go run ./cmd/genwire   (or npm run wire:gen)
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

const outPath = "wails/frontend/src/net/wire.gen.ts"

// fieldOverrides keeps generated fields aligned with the stronger literal
// unions the client already uses, where the Go side is a plain string.
var fieldOverrides = map[string]map[string]string{
	"WorldEntity": {"Kind": "EntityKind", "Facing": "number | string"},
	"HousePlayer": {"Facing": "number | string"},
	"Item":        {"Rarity": "Rarity"},
}

var entityKindValues = []string{"player", "npc", "pet"}

type gen struct {
	structs  map[string]*ast.StructType // name -> struct (both packages)
	under    map[string]string          // named non-struct type -> underlying kind ("string", "number")
	enumVals map[string][]string        // named type -> const literal values
	order    []string                   // struct decl order (protocol first)
	emitted  map[string]bool
	msgTypes []string
}

func main() {
	g := &gen{
		structs:  map[string]*ast.StructType{},
		under:    map[string]string{},
		enumVals: map[string][]string{},
		emitted:  map[string]bool{},
	}
	// Protocol structs emit eagerly in declaration order; internal/game
	// structs are collected for lookup and emitted on demand via references.
	g.parseDir("internal/protocol", true)
	g.parseDir("internal/game", false)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/genwire (go run ./cmd/genwire). DO NOT EDIT.\n")
	b.WriteString("// Source of truth: internal/protocol/messages.go (+ internal/game structs it references).\n\n")

	// MessageType union.
	b.WriteString("export type MessageType =\n")
	for i, v := range g.msgTypes {
		sep := " |"
		if i == len(g.msgTypes)-1 {
			sep = ";"
		}
		fmt.Fprintf(&b, "  %q%s\n", v, sep)
	}
	b.WriteString("\n")

	// Literal-union aliases.
	b.WriteString("/** Entity classes carried in WorldEntity.kind. */\n")
	fmt.Fprintf(&b, "export type EntityKind = %s;\n\n", quotedUnion(entityKindValues))
	if vals := g.enumVals["Rarity"]; len(vals) > 0 {
		fmt.Fprintf(&b, "export type Rarity = %s;\n\n", quotedUnion(vals))
	}

	// Interfaces: all protocol structs in declaration order, plus any game
	// structs referenced transitively.
	for _, name := range g.order {
		g.emitStruct(&b, name)
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("genwire: wrote %s (%d types, %d message types)\n", outPath, len(g.emitted), len(g.msgTypes))
}

func (g *gen) parseDir(dir string, inOrder bool) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		fatal(err)
	}
	for _, pkg := range pkgs {
		// Declaration order across files: sort filenames for determinism.
		var files []string
		for name := range pkg.Files {
			files = append(files, name)
		}
		sort.Strings(files)
		for _, name := range files {
			g.parseFile(pkg.Files[name], inOrder)
		}
	}
}

func (g *gen) parseFile(f *ast.File, inOrder bool) {
	for _, d := range f.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok {
			continue
		}
		switch gd.Tok {
		case token.TYPE:
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				switch t := ts.Type.(type) {
				case *ast.StructType:
					if _, dup := g.structs[ts.Name.Name]; !dup {
						g.structs[ts.Name.Name] = t
						if inOrder {
							g.order = append(g.order, ts.Name.Name)
						}
					}
				case *ast.Ident:
					g.under[ts.Name.Name] = identKind(t.Name)
				}
			}
		case token.CONST:
			for _, spec := range gd.Specs {
				vs := spec.(*ast.ValueSpec)
				tname := ""
				if id, ok := vs.Type.(*ast.Ident); ok {
					tname = id.Name
				}
				for i, v := range vs.Values {
					bl, ok := v.(*ast.BasicLit)
					if !ok || bl.Kind != token.STRING {
						continue
					}
					val := strings.Trim(bl.Value, `"`)
					switch {
					case tname == "MessageType":
						g.msgTypes = append(g.msgTypes, val)
					case tname != "" && i < len(vs.Names):
						// Typed string const — collect for enum aliases.
						g.enumVals[tname] = append(g.enumVals[tname], val)
					}
				}
			}
		}
	}
}

// emitStruct writes one interface and recursively emits referenced named
// structs (e.g. game.Item). Names absent from g.structs are scalar aliases.
func (g *gen) emitStruct(b *strings.Builder, name string) {
	if g.emitted[name] {
		return
	}
	st, ok := g.structs[name]
	if !ok {
		return
	}
	g.emitted[name] = true
	var pending []string // referenced structs to emit after this one

	fmt.Fprintf(b, "export interface %s {\n", name)
	for _, field := range st.Fields.List {
		tag := fieldTag(field)
		if tag == "-" {
			continue
		}
		jname, opts := splitTag(tag)
		if jname == "" {
			if len(field.Names) == 0 {
				continue // embedded
			}
			jname = lowerFirst(field.Names[0].Name)
		}
		t := g.tsType(field.Type, name, jname, &pending)
		opt := ""
		if strings.Contains(opts, "omitempty") {
			opt = "?"
			t = strings.TrimSuffix(t, " | null")
		}
		if override, ok := fieldOverrides[name][fieldName(field)]; ok {
			t = override
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", jname, opt, t)
	}
	b.WriteString("}\n\n")

	for _, dep := range pending {
		g.emitStruct(b, dep)
	}
}

func (g *gen) tsType(e ast.Expr, parent, jname string, pending *[]string) string {
	switch t := e.(type) {
	case *ast.Ident:
		return g.namedType(t.Name, pending)
	case *ast.StarExpr:
		return g.tsType(t.X, parent, jname, pending) + " | null"
	case *ast.ArrayType:
		return g.tsType(t.Elt, parent, jname, pending) + "[]"
	case *ast.MapType:
		return fmt.Sprintf("Record<string, %s>", g.tsType(t.Value, parent, jname, pending))
	case *ast.SelectorExpr:
		// Cross-package (game.X) or encoding/json.RawMessage.
		if id, ok := t.X.(*ast.Ident); ok && id.Name == "json" && t.Sel.Name == "RawMessage" {
			return "unknown"
		}
		return g.namedType(t.Sel.Name, pending)
	case *ast.InterfaceType:
		return "unknown"
	}
	return "unknown"
}

func (g *gen) namedType(name string, pending *[]string) string {
	if name == "MessageType" {
		return "MessageType"
	}
	if k := scalarKind(name); k != "" {
		return k
	}
	if u, ok := g.under[name]; ok {
		return u
	}
	if _, ok := g.structs[name]; ok {
		*pending = append(*pending, name)
		return name
	}
	return name
}

func scalarKind(goName string) string {
	switch goName {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "byte", "rune":
		return "number"
	}
	return ""
}

func identKind(goName string) string {
	if k := scalarKind(goName); k != "" {
		return k
	}
	return "string"
}

func fieldTag(f *ast.Field) string {
	if f.Tag == nil {
		return ""
	}
	return strings.Trim(f.Tag.Value, "`")
}

func splitTag(tag string) (name, opts string) {
	// tag looks like: json:"name,omitempty"
	idx := strings.Index(tag, `"`)
	if idx < 0 {
		return "", ""
	}
	rest := tag[idx+1:]
	end := strings.Index(rest, `"`)
	if end < 0 {
		return "", ""
	}
	inner := rest[:end]
	parts := strings.SplitN(inner, ",", 2)
	name = parts[0]
	if len(parts) > 1 {
		opts = parts[1]
	}
	return name, opts
}

func fieldName(f *ast.Field) string {
	if len(f.Names) == 0 {
		return ""
	}
	return f.Names[0].Name
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func quotedUnion(vals []string) string {
	out := make([]string, len(vals))
	for i, v := range vals {
		out[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(out, " | ")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "genwire:", err)
	os.Exit(1)
}
