import Phaser from "phaser";
import { loadSpritesheet } from "./assets";
import { ENEMY_KINDS, enemyTextureKey, type EnemyKind } from "./enemies";

const ENEMY_BASE = "/assets/enemies";

const ENEMY_PNG_PATH: Record<EnemyKind, string> = {
  goblin: `${ENEMY_BASE}/goblin.png`,
  dire_wolf: `${ENEMY_BASE}/dire_wolf.png`,
  stone_imp: `${ENEMY_BASE}/stone_imp.png`,
};

let sheetLoad: Promise<void> | null = null;

/** Load the pixel-art enemy sheets (Heroes 99 layout, generated by scripts/gen-enemy-sprites.mjs). */
export function ensureEnemyTextures(scene: Phaser.Scene): Promise<void> {
  if (ENEMY_KINDS.every((kind) => scene.textures.exists(enemyTextureKey(kind)))) {
    return Promise.resolve();
  }
  if (!sheetLoad) {
    sheetLoad = Promise.all(
      ENEMY_KINDS.map((kind) =>
        loadSpritesheet(scene, enemyTextureKey(kind), ENEMY_PNG_PATH[kind]),
      ),
    )
      .then(() => undefined)
      .finally(() => {
        sheetLoad = null;
      });
  }
  return sheetLoad;
}
