import Phaser from "phaser";
import { loadSpritesheet } from "./assets";
import { ENEMY_KINDS, enemyTextureKey, isDollEnemy, type EnemyKind } from "./enemies";

/** Doll kinds render through Spine — only sheet kinds need PNG loads. */
const SHEET_KINDS = ENEMY_KINDS.filter((kind) => !isDollEnemy(kind));

const ENEMY_PNG_PATH: Partial<Record<EnemyKind, string>> = {};

let sheetLoad: Promise<void> | null = null;

/** Load the pixel-art enemy sheets (Heroes 99 layout, generated by scripts/gen-enemy-sprites.mjs). */
export function ensureEnemyTextures(scene: Phaser.Scene): Promise<void> {
  if (SHEET_KINDS.every((kind) => scene.textures.exists(enemyTextureKey(kind)))) {
    return Promise.resolve();
  }
  if (!sheetLoad) {
    sheetLoad = Promise.all(
      SHEET_KINDS.map((kind) =>
        loadSpritesheet(scene, enemyTextureKey(kind), ENEMY_PNG_PATH[kind]!),
      ),
    )
      .then(() => undefined)
      .finally(() => {
        sheetLoad = null;
      });
  }
  return sheetLoad;
}
