import { BeginCursorCapture, EndCursorCapture, RecenterCursor } from "../../wailsjs/go/app/App";

/**
 * Orbit cursor capture. While a drag with the orbit `button` is active the
 * cursor is held inside the window so the drag can't run off the screen edge.
 *
 * Two strategies, best first:
 *  1. requestPointerLock — where the webview supports it.
 *  2. OS capture via the Wails bindings — ClipCursor to the window + hidden
 *     cursor + warp back to center whenever it nears an edge. WebView2's
 *     pointer lock is unreliable, so this is usually the active path in-app.
 *
 * OrbitControls rotates on clientX/clientY deltas, which freeze under either
 * confinement — so while a capture is active we rewrite each pointermove/up's
 * clientX/Y with a virtual cursor accumulated from movementX/Y before the
 * controls see it (document capture runs before their document bubble
 * listeners). If neither strategy engages the virtual cursor simply tracks
 * the real one and orbiting degrades to the old behavior.
 */
export function attachOrbitPointerLock(dom: HTMLElement, button = 2): () => void {
  let active = false;
  let osCapture = false;
  let x = 0;
  let y = 0;
  let skipMove = false;
  let fallbackTimer = 0;

  const callGo = (fn: () => Promise<void>) => {
    try {
      void fn().catch(() => undefined);
    } catch {
      /* wails bindings absent (browser/tests) — nothing to capture */
    }
  };

  const patch = (e: PointerEvent) => {
    x += e.movementX;
    y += e.movementY;
    Object.defineProperty(e, "clientX", { value: x });
    Object.defineProperty(e, "clientY", { value: y });
  };

  const startOsCapture = () => {
    if (osCapture || !active || document.pointerLockElement === dom) return;
    osCapture = true;
    document.documentElement.style.cursor = "none";
    callGo(BeginCursorCapture);
  };

  const stopOsCapture = () => {
    if (!osCapture) return;
    osCapture = false;
    document.documentElement.style.cursor = "";
    callGo(EndCursorCapture);
  };

  const end = () => {
    active = false;
    window.clearTimeout(fallbackTimer);
    stopOsCapture();
    if (document.pointerLockElement === dom) document.exitPointerLock();
  };

  const onDown = (e: PointerEvent) => {
    if (e.button !== button) return;
    active = true;
    x = e.clientX;
    y = e.clientY;
    try {
      const req = dom.requestPointerLock() as unknown as Promise<void> | undefined;
      req?.catch?.(() => undefined);
    } catch {
      /* pointer lock unsupported — OS capture takes over below */
    }
    // If the lock doesn't engage almost immediately, take over at OS level.
    fallbackTimer = window.setTimeout(() => {
      if (active && document.pointerLockElement !== dom) startOsCapture();
    }, 60);
  };

  const onMove = (e: PointerEvent) => {
    if (!active) return;
    // The button released somewhere we can't see (capture lost mid-drag) —
    // stop rather than leak the virtual cursor into normal UI.
    if (!(e.buttons & (1 << button))) {
      end();
      return;
    }
    if (skipMove) {
      // Synthetic move generated by our RecenterCursor warp — absorbing its
      // delta would corrupt the virtual cursor.
      skipMove = false;
      return;
    }
    patch(e);
    if (osCapture) {
      // Keep the physical cursor away from the window edges so movement
      // deltas keep flowing — warp it back to the center when it gets close.
      const margin = 80;
      if (e.clientX < margin || e.clientY < margin || e.clientX > window.innerWidth - margin || e.clientY > window.innerHeight - margin) {
        skipMove = true;
        callGo(RecenterCursor);
      }
    }
  };

  const onUp = (e: PointerEvent) => {
    if (!active || e.button !== button) return;
    patch(e);
    end();
  };

  const onLockChange = () => {
    if (document.pointerLockElement === dom) stopOsCapture();
  };

  dom.addEventListener("pointerdown", onDown);
  document.addEventListener("pointermove", onMove, true);
  document.addEventListener("pointerup", onUp, true);
  document.addEventListener("pointercancel", end, true);
  document.addEventListener("pointerlockchange", onLockChange);
  document.addEventListener("pointerlockerror", startOsCapture);
  window.addEventListener("blur", end);

  return () => {
    end();
    dom.removeEventListener("pointerdown", onDown);
    document.removeEventListener("pointermove", onMove, true);
    document.removeEventListener("pointerup", onUp, true);
    document.removeEventListener("pointercancel", end, true);
    document.removeEventListener("pointerlockchange", onLockChange);
    document.removeEventListener("pointerlockerror", startOsCapture);
    window.removeEventListener("blur", end);
  };
}
